### ISSUE TITLE
[VT-93] vit daemon

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#115]
_David Patrick on 2014-06-19T16:51:03Z says:_ 

 This feature suggestion is for a "wrapper" daemon, used to start vit and keep it "running". The daemon would have a configurable refresh cycle (default: 60sec) that kept onscreen times (semi) accurate, things like active time, mod times, countdowns etc. This would also allow (semi) real-time events to take place, without the vit user having to refresh the screen every minute, things like tw-scheduled occurrences (like tasks being auto-deleted with wait:) or external changes from other clients or users. 
As a bonus, if the daemon were running, vit could show the current time and date in the header.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-19T16:51:03Z
Modified: 2017-02-01T19:08:48Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2014-06-19T19:25:20Z says:_ 

 Sounds reasonable. It might make sense to also look into using inotify. This would let VIT know whenever certain files change, e.g. pending.data.

**Comment by thehunmonkgroup** [comment]
Can be accomplished with the auto-refresh tools: https://github.com/vit-project/vit/blob/2.x/CUSTOMIZE.md#auto-refreshing-vits-interface
