### ISSUE TITLE
[VT-99] search history

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#121]
_David Patrick on 2014-06-28T20:18:52Z says:_ 

 This is similar to the recently added command history (scrolling) but just for search-terms used. For example, hit "/" or "?" and then up-arrow, and what happens? currently nothing, but scrolling through the history of search-terms used would be excellent.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-28T20:18:52Z
Modified: 2015-03-04T06:12:46Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-04T06:12:46Z says:_ 

 I agree this would be nice. The search prompt uses different code from the other prompts (add, modify, filter, etc). Ideally we would merge that code, unless there is something I'm missing. I think the reason for keeping it separate was so that "n" could be interpreted as "next match" after a search, but I think we can still do that.

**Comment by thehunmonkgroup** [comment]
VIT 2.x alpha 1 has been released, tit does include search history, although forward and reverse search history has not been integrated yet.

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by fdela** [comment]
This works now. This issue can be closed.
