### ISSUE TITLE
[VT-101] Tasks do not display if filter applied on scrolled-down list

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#123]
_Nemo Inis on 2014-10-03T00:44:04Z says:_ 

 if you have a lot of tasks (more than 1 VIT's screenful), and scroll down with the down arrow or mousewheel to see the rest of the tasks; then use a filter that would only show a few tasks: the tasks do not show. You have to cancel your filter, scroll back to the top of the big task list, then re-apply your filter.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-03T00:44:04Z
Modified: 2014-10-03T05:21:02Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2014-10-03T05:21:02Z says:_ 

 I can reproduce this. Have you noticed if this happens for anything besides filter? For example, I couldn't reproduce by changing reports.

**Comment by fdela** [comment]
No issue as of 1e1d010; closing
