### ISSUE TITLE
reading of projects is broken

### ISSUE THREAD

**Issue by baszoetekouw** [vit-project/vit#14]
In read.pl, vit reads a list of all available projects to use for tab complation.  However, the parsing of taskwarrior's output is broken, causing vit to include projects like "------" and "  " in the tab completion list.

It should be striaghtforward to reuse the parsing from the task patch of #5.  I'll see if I can get around to fixing this before 1.3.

**Comment by scottkosty** [comment]
Sounds good. Indeed, it seems to work well for the tab completion of tags.

**Comment by scottkosty** [comment]
@baszoetekouw will you be able to come up with a patch for this soon?

**Comment by scottkosty** [comment]
@baszoetekouw I'm guessing you're pretty busy. Should we put this off to v1.4? If I remember correctly, this is not a regression, right?

**Comment by scottkosty** [comment]
I think this is not a regression, so I'm taking off the 1.3 milestone.

**Comment by fdela** [comment]
Since 1.3 is in security-fix-only mode, and `read.pl` is nowhere to be found on 2.x branch, I guess this issue can be closed?
