### ISSUE TITLE
[VT-119] Improve handling of quotes in task titles

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#140]
_Larry Hynes on 2015-04-17T21:07:04Z says:_ 

 I've been in touch with Scott about this via email and he felt that we might have a broader discussion here regarding vit's handling of quotes in task titles.

It seems that vit used to quote the entire title string, but that was removed to address [#114 | https://bug.tasktools.org/browse/VT-114] and [#111 | https://bug.tasktools.org/browse/VT-111].

I'm not sure what the best way to handle this is. As it stands I would be happy with a better error message, or better handling of the error message, but long-term I do think it would be great if vit could handle these cases without throwing an error.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-04-17T21:07:04Z
Modified: 2015-04-26T16:56:59Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-04-22T17:25:12Z says:_ 

 Thanks for writing this up Larry. My idea is to have a .vitrc variable that contains the characters that the user wants to be escapted. For example, you could put a quote in there.

**Comment by taskwarrior** [comment]
_Larry Hynes on 2015-04-26T16:56:59Z says:_ 

 That's a novel solution. I can see myself using it, and maybe putting '!' in there along with quotes. :)

**Comment by pekcheey** [comment]
I am wont to using single quote.. so as a workaround, before the proper solution comes to pass, the following seems to work.

```
cy@raspberrypi ~/s/vit> git diff vit/util.py
diff --git a/vit/util.py b/vit/util.py
index 02a824b..c6188f2 100644
--- a/vit/util.py
+++ b/vit/util.py
@@ -13,7 +13,7 @@ def clear_screen():

 def string_to_args(string):
     try:
-      return shlex.split(string)
+      return shlex.split(string.replace("'", "\\'").replace('"','\\"'))
     except ValueError:
       return []

cy@raspberrypi ~/s/vit>

```

**Comment by awilkins** [comment]
Sorry to necro this, but should this kind of escaping apply in other places?

e.g. using a quote in an `A`nnotation without shell-escaping it means the annotation will not work.

**Comment by thehunmonkgroup** [comment]
I'd need a test case to reproduce an actual problem, preferably using https://github.com/vit-project/vit/blob/2.x/scripts/generate-dummy-install.sh
