### ISSUE TITLE
[VT-129] not finding perl correctly

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#150]
_Eric Hymowitz on 2016-06-03T17:59:55Z says:_ 

 Trying to configure VIT.  Exits with error:

`checking for task... /usr/local/bin/task`
`checking for perl... /usr/local/bin/perl`
`configure: error: can not continue... perl must be installed as /usr/bin/perl`
`confgiure: hint: try "sudo ln -s /usr/local/bin/perl /usr/bin/perl"`

I have already done this.  /usr/bin/perl is a soft link to /usr/local/bin/perl .  However, I presume that because /usr/local/bin is before /usr/bin in my $PATH , it refuses to realize this.  It sees /usr/local/bin/perl in my $PATH and stops.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-06-03T17:59:55Z
Modified: 2017-12-14T03:23:01Z
```

**Comment by thehunmonkgroup** [comment]
https://github.com/scottkosty/vit/pull/167 would eliminate this issue, and no longer require the symlink.

**Comment by fdela** [comment]
1.3 branch is no longer receiving non-security updates.
