### ISSUE TITLE
Window doesn't self-update. 

### ISSUE THREAD

**Issue by maikeldotuk** [vit-project/vit#169]
So, let's say I have started a task as mentioned in issue #168. Now I have a window that shows how long I've been doing it, together with all other tasks. 
There's just one problem: **That window content never updates**

Ultimately ended up doing: while true; task; sleep 10; end (I use Fish shell) to have that duration active updated. 

I think Vit would be feature-complete if it had the ability to remain updated by refreshing its main window content after certain amount of time. Could this feature be added easily?

**Comment by scottkosty** [comment]
@maikeldotuk I think there are a few related requests. See, for example, #151. Also, I don't know if you're interested but you might like [https://taskwarrior.org/docs/timewarrior/what.html](Timewarrior). I've never used it but since you're interested in the duration, perhaps you'll find it useful.

**Comment by maikeldotuk** [comment]
I checked that issue before I posted. It kind of overcomplicated the simple. In that issue they talk about some sort of inotify implementation. While I'm just talking about a refresh, the equivalent of pressing control+L every few seconds.This feature is much easier to implement. It just means a loop for whatever happens after clicking ctr+L with a user defined number of seconds. On 8 Mar 2019 02:56, Scott Kostyshak <notifications@github.com> wrote:@maikeldotuk I think there are a few related requests. See, for example, #151. Also, I don't know if you're interested but you might like https://taskwarrior.org/docs/timewarrior/what.html. I've never used it but since you're interested in the duration, perhaps you'll find it useful.

**Comment by maikeldotuk** [comment]
I just checked the Timewarrior link, read the whole thing, I rather avoid experimenting otherwise I won't ever escape of this rabbit hole. 

On Friday, March 08, 2019 02:56 GMT, Scott Kostyshak <notifications@github.com> wrote:
 
@maikeldotuk I think there are a few related requests. See, for example, #151. Also, I don't know if you're interested but you might like https://taskwarrior.org/docs/timewarrior/what.html. I've never used it but since you're interested in the duration, perhaps you'll find it useful.

**Comment by scottkosty** [comment]
@maikeldotuk OK let's keep this issue as a separate one then. From what I understand, you want the update even if there has been no change to the task database. Because that way, the durations will still update.

**Comment by maikeldotuk** [comment]
Exactly. It's just basically the same we achieve with aWhile true; task; sleep 60; clear; endIn Fish shell. The problem being that's just task, not vit so the interactivity is lost On 8 Mar 2019 05:42, Scott Kostyshak <notifications@github.com> wrote:@maikeldotuk OK let's keep this issue as a separate one then. From what I understand, you want the update even if there has been no change to the task database. Because that way, the durations will still update.

**Comment by maikeldotuk** [comment]
A 1 minute refresh seems sensible.

**Comment by scottkosty** [comment]
@maikeldotuk 1 minute could be fine. In any case it should be configurable (in .vitrc). 

If anyone is interested in working on a patch for this, let me know in advance so we can discuss the interface and implementation.

**Comment by scottkosty** [comment]
@maikeldotuk you might be interested in testing the patch here https://github.com/scottkosty/vit/pull/162. It seems to be set to 30 minutes, but you could change it to 1 minute. Please let me know if you test it.

**Comment by thatnerdjosh** [comment]
I had this issue too, but I discovered `ctrl+l` hotkey to refresh, this seems to work fine for me... same like reloading a browser window

**Comment by thehunmonkgroup** [comment]
I'm not confident there's a better solution than simply using ```ctrl+l``` -- I'm pretty confident an entire report refresh every minute would be disruptive, as it could happen right in the middle of some action you're taking.

It *might* be possible to put some kind of listener in that would reset the count on any key press, but still, that seems fraught with issues.

I don't actually see the core TaskWarrior or VIT interfaces being intended for 'real time' updates, and suspect that trying to make them such would cause more harm to the architecture than benefit created.

Pretty sure there are other tools that are better suited for this job.

**Comment by thehunmonkgroup** [comment]
Can be accomplished with the auto-refresh tools: https://github.com/vit-project/vit/blob/2.x/CUSTOMIZE.md#auto-refreshing-vits-interface
