### ISSUE TITLE
Use of uninitialized value $prev_id in concatenation (.)

### ISSUE THREAD

**Issue by nblock** [vit-project/vit#170]
When running some reports (tested with `completed` and `summary`) the following error occurs and vit exits:
```
VIT fatal error: (converted from warning) Use of uninitialized value $prev_id in concatenation (.) or string at /usr/local/bin/vit line 2142, <IN> line 2.
```

* vit version: `1.3`
* task version: `2.5.1`
* perl version: `5.28.1`

**Comment by scottkosty** [comment]
There's currently some work being done under the hood for vit 2.0. Let's wait and see if that fixes this problem.

**Comment by thehunmonkgroup** [comment]
@nblock VIT 2.x alpha 1 has been released, think you can investigate if this issue still occurs there?

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by nblock** [comment]
Could no longer reproduce it on 2.0a1, thx!

**Comment by scottkosty** [comment]
@nblock great, thanks for confirming!
