### ISSUE TITLE
Command D always deletes a task

### ISSUE THREAD

**Issue by nblock** [vit-project/vit#171]
The help text for the command `D` has the following description: `denotate if over annotation, delete task if on first line`.

If I place the cursor on a task's annotation and hit `D`, the task is deleted instead of the selected annotation being removed.

![vit-denotate](https://user-images.githubusercontent.com/131119/56093141-fcd61400-5ec4-11e9-8886-9c2cd8d71b46.png)

* vit version: `1.3`
* task version: `2.5.1`
* perl version: `5.28.1`

**Comment by scottkosty** [comment]
Strange. I don' think that should happen. There's currently some work being done under the hood for vit 2.0. Let's wait and see if that fixes this problem.

**Comment by thehunmonkgroup** [comment]
@nblock VIT 2.x alpha 1 has been released, and includes a separate denotation popup window, triggered with the keybinding 'E' by default.

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by nblock** [comment]
Awesome, works nicely on 2.0a1!

**Comment by scottkosty** [comment]
@nblock great, thanks for confirming!
