### ISSUE TITLE
Unable to display and input uppercase icelandic characters

### ISSUE THREAD

**Issue by esijg** [vit-project/vit#174]
Tested in v1.3 on Ubuntu 19.04.

Trying to add the task "This is a test Þ Ö Á É Ý Ú Í Ó Ð Æ" results in the following.

![Skjámynd frá 2019-05-18 11-13-16](https://user-images.githubusercontent.com/2924543/57968761-1bb14580-795e-11e9-9c62-6046060606b4.png)

![Skjámynd frá 2019-05-18 11-13-38](https://user-images.githubusercontent.com/2924543/57968773-4d2a1100-795e-11e9-8848-8e58b28e02f4.png)

It also gets saved incorrectly. Note that lowercase letters are fine. All older tasks (added with different programs) are also affected as long as they feature uppercase icelandic letters.

Simple reproduction
Add: Þ
becomes
Add:  ^

**Comment by scottkosty** [comment]
Thanks for this report. Dang it, when we added support for other character sets at 77a9f97b I was hoping it would fix problems like this. Just to be sure, everything works fine when you add the task using Taskwarrior directly, right?

**Comment by esijg** [comment]
Yes, Taskwarrior works fine. Tasks added in taskwarrior with uppercase iceland-specific characters display correctly in Taskwarrior. But those tasks do get displayed incorrectly in Vit. 

I've now tested this on two of my computers (both running Ubuntu 19.04) with the same results.

This is a bit of an odd bug as I've experienced and reported a lot of bugs in software regarding inputting and displaying icelandic characters throughout the years. Often they manage to display the accented characters (í á é, etc...) correctly but fail at more specific characters like Þ and Ð. I've never seen a problem where only capital letters would get mangled in such way. 

One other thing. The terminal cursor also gets displayed in the wrong location. In the first screenshot it was supposed to be on the end of the line, but instead was displayed a bit to the left to it's actual location. For example, when writing "Þ" vit displays "  ^", with the cursor sitting on the empty space. So for each new uppercase icelandic character written two "characters" get added but the mouse only moves one spot forward.

**Comment by scottkosty** [comment]
Thanks for these extra details. VIT 2.0 is in the works and will be a big change. There's a chance this problem will be solved from the restructuring. Let's wait until then and then come back to this.

> One other thing. The terminal cursor also gets displayed in the wrong location.

This is not surprising, given the main bug. Apparently it's not trivial to detect the length of a word written in an unsupported languages, because many characters require multiple bytes for each character. If it sounds like I know what I'm talking about, I don't :). But I will be interested in learning more and trying to fix this issue if VIT 2.0 doesn't magically fix it.

**Comment by thehunmonkgroup** [comment]
@johannesgunnar VIT 2.x alpha 1 has been released, think you can investigate if this issue still occurs there?

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by esijg** [comment]
can confirm that v2.0.0a1 seems to have fixed the issue. Can't promise with special characters from other languages, but icelandic capital special characters work perfectly fine now.

Thank you very much.

**Comment by thehunmonkgroup** [comment]
Great, thanks for confirming!
