### ISSUE TITLE
Readline edit shortcuts for command bar

### ISSUE THREAD

**Issue by thehunmonkgroup** [vit-project/vit#176]
VIT 2.x does not yet have a full compliment of [Readline](https://tiswww.case.edu/php/chet/readline/rltop.html) shortcuts. Currently only 'go to line beginning' and 'go to line end' are implemented.

**Comment by nfraprado** [comment]
I'd like to help with these. Are all shortcuts really needed though? It seems there are a lot of obscure ones on [Readline User Interface](https://tiswww.case.edu/php/chet/readline/rluserman.html). Wouldn't these ones [here](https://gist.github.com/jottr/a2351377b7584abf100b), under Cursor Movement and Copy & Paste, be enough?

**Comment by thehunmonkgroup** [comment]
I had only planned on implementing a subset of the shortcuts for sure.

Here are the ones on my short list:

```
Jump backward one character 	Ctrl + B / ←
Jump backward one word 	Meta + B
Delete one character 	Ctrl + D
Delete one word 	Meta + D
Jump forward one character 	Ctrl + F / →
Jump forward one word 	Meta + F
Delete previous character 	Ctrl + H
Transpose characters 	Ctrl + T
Kill (cut) forwards to the end of the line 	Ctrl + K
Kill (cut) backwards to the start of the line 	Ctrl + U
Kill (cut) forwards to the end of the current word 	Meta + D
Kill (cut) backwards to the start of the current word 	Ctrl + W
Clear screen 	Ctrl + L (already implemented as 'refresh current report')
Go to beginning of line    Ctrl + A (already implemented)
Go to end of line    Ctrl + E (already implemented)
```

This project would probably be a good place to start: https://github.com/rr-/urwid_readline

IIRC it's overkill on features, and I don't really want to add another dependency, but it would probably at least shorten the implementation curve.
