### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: 'local' / TZ env not setup by default in WSL/ubuntu

### ISSUE THREAD

**Issue by fmeynadier** [vit-project/vit#187]
Hi,

vit has the same problem as taskwiki (https://github.com/tbabej/taskwiki/issues/110) when installed in Windows Subsystem for Linux running Ubuntu 18.04. 

In this particular setup, running `vit` right after install (and initial configuration) ends with 

`pytz.exceptions.UnknownTimeZoneError: 'local'`

Simply defining the TZ environment variable to a correct "Continent/City" timezone solves the issue.

Not sure if it should be filed as a pytz issue, though (I don't see it in their issue tracker https://bugs.launchpad.net/pytz). 

Anyway thanks for this rewriting !

**Comment by thehunmonkgroup** [comment]
Yeah, this isn't really a problem with VIT, but to smooth things out I've added a section to the FAQ about it: https://github.com/scottkosty/vit/blob/2.x/FAQ.md#how-do-i-fix-unknowntimezoneerror-in-windows-subsystem-for-linux
