### ISSUE TITLE
MAX_COLUMN_WIDTH = 60 is to small

### ISSUE THREAD

**Issue by jspricke** [vit-project/vit#190]
For me this results in line breaks in the descriptions, and lot's of space to the right of it. So I patched it to 600. I see two options, either make it a configuration option, or compute use shutil.get_terminal_size and adopt the line length to the terminal. What would you prefer (I can probably come up with code for both of it)?

Thanks for porting vit to Python!

**Comment by thehunmonkgroup** [comment]
Yeah, the column width calculation code needs more work. I'm already using the screen width and dynamically reducing wider columns, see resize_columns() in task_list.py

I'd be open to more optimizations to that code, although I recall it being fairly tricky to find an algorithm that worked well across a wide range of possible report/column scenarios -- you can't simply steal width from every column to make everything fit.

I think ideally there would be no need for MAX_COLUMN_WIDTH.

**Comment by sanjayankur31** [comment]
Could there be a configuration option that allows setting percentages for the column widths maybe? Let there be "sane defaults", but it'll also let users tweak things easily?

**Comment by thehunmonkgroup** [comment]
@sanjayankur31 pretty sure that would quickly become too complicated, as there are many reports, each with their own column configurations.

**Comment by sanjayankur31** [comment]
Hrm, I wonder how `task` does it. :thinking:

**Comment by thehunmonkgroup** [comment]
```task``` has the advantage of knowing that it will only have to display N rows of a report. We don't have that luxury, because the user can scroll down. I briefly reviewed ```task```'s strategy, and it seemed too processor heavy for VIT's use case.

**Comment by sanjayankur31** [comment]
Ah, right---it's quite a complex problem then. Maybe just let `MAX_COLUMN_WIDTH` be configurable in the meantime and let users set it?

**Comment by thehunmonkgroup** [comment]
I'm a bit resistant to add a config option for max column width, I'd rather see the algorithm improved and eliminate that idea entirely.

I'm hoping @jspricke will take a crack at that.

**Comment by thehunmonkgroup** [comment]
Resolved by #199
