### ISSUE TITLE
[RFE] [2.x] Please include tests/__init__.py in the pypi tarball (needed for tests to be run)

### ISSUE THREAD

**Issue by sanjayankur31** [vit-project/vit#195]
The tar doesn't include `tests/__init__.py`, probably because it's an empty file, but this is needed for unittests to find the tests in `tests`, so it'll need to be included in the manifest (for the pypi tar).

**Comment by thehunmonkgroup** [comment]
should be fixed in https://github.com/scottkosty/vit/commit/537dbe13031345b5e39bfce923bed58db0924b64 -- can you verify?

**Comment by thehunmonkgroup** [comment]
Whoops, I tagged the wrong issue number above.

I'm not quite clear how to address this issue. I did find an SO post that suggested adding this to the manifest:

```recursive-include test *.py```

Will that do it?

**Comment by sanjayankur31** [comment]
Yes, that seems to work. I added the line and then ran `python setup.py sdist`. The tar in the `dist` folder contains the `__init__.py` file.

**Comment by thehunmonkgroup** [comment]
Should be all set.
