### ISSUE TITLE
[2.x] Allow disabling mouse support?

### ISSUE THREAD

**Issue by sanjayankur31** [vit-project/vit#197]
It seems like the mouse support takes away from some of the terminal emulator's handling of the mouse. For example, one can no longer left/right click on a link in the task list. 

Could some mouse actions be let through, or maybe a config option to disable mouse support so that the terminal emulator can handle these things natively? It's meant to be a terminal tool, so I don't think mouse support is a necessary feature.

**Comment by scottkosty** [comment]
ranger has the config option `mouse_enabled`. Perhaps we could have the same.

**Comment by thehunmonkgroup** [comment]
@sanjayankur31 should be fixed by https://github.com/scottkosty/vit/commit/fca6eb74817e07c7e88179805396bb219b35ff6d -- please confirm.

This adds a ```mouse``` config option to the ```vit``` section of ```config.ini```, which defaults to False, as is sensible for a terminal tool :)

**Comment by sanjayankur31** [comment]
Tested both enabling and disabling mouse support in a virtual environment. Works :+1:
