### ISSUE TITLE
[2.x] {TASKID} returns task uuid instead of ID

### ISSUE THREAD

**Issue by sanjayankur31** [vit-project/vit#200]
Hello,

I noticed that `{TASKID}` was being replaced by the uuid of the task, and not the ID. Is this by design? Maybe we could `TASKID` be the ID and `TASKUUID` be the uuid just to prevent confusion?

**Comment by thehunmonkgroup** [comment]
This is leftover syntax from 1.x, and I agree this is an issue we need to address. I have a different proposal though:

We eliminate ```{TASKID}``` and replace it with ```{TASK_UUID}```. Reasons why:

1. Task IDs change, while UUIDs are consistent
1. Any command that takes a task ID also takes a task UUID
1. Supporting both ```{TASKID}``` and ```{TASK_UUID}``` could be potentially confusing, and result in more support requests.

Thoughts?

**Comment by sanjayankur31** [comment]
Yes, that sounds good!

**Comment by scottkosty** [comment]
Sounds good to me too. I can't think of a situation where relying on the task ID would be preferred to relying on the task UUID.
