### ISSUE TITLE
Respect position in list when deleting or marking tasks as done

### ISSUE THREAD

**Issue by esijg** [vit-project/vit#201]
Right now it seems like VIT moves your selection to the top of your list whenever you mark tasks as done or delete them. Which makes it relatively cumbersome to go through task lists to clean up or mark multiple tasks as done. A more sensible approach in my opinion would be to move selection one item down when the currently selected item disappears.

or is this already an option somewhere perhaps?

**Comment by thehunmonkgroup** [comment]
I've noticed this annoying behavior as well.

I'm quite busy now, so I may not have time to get to this in the near future. It also might be a bit tricky, right now I'm not tracking previous position of a task, which will be necessary to properly implement this enhancement.

I'd like to get this fixed prior to 2.0.0 release.

**Comment by thehunmonkgroup** [comment]
https://github.com/scottkosty/vit/commit/9960f135bb96142c517a865fd366aac855ecc414 should fix this issue, please try out latest master to verify.

**Comment by esijg** [comment]
Can confirm. this seems to be working now. Thank you very much <3
