### ISSUE TITLE
Report filter not applied

### ISSUE THREAD

**Issue by nfraprado** [vit-project/vit#202]
I just tried vit 2.x and for my surprise the filters assigned to reports in the taskwarrior config aren't applied when seeing a report from within vit. From DEVELOPMENT.md I got that vit 2.x gets the information from task export rather than from taskwarrior's output, which is why the report filter isn't applied.
In my opinion, this is undesired behavior. The filter associated with a report should be applied whenever that report is viewed on vit (also probably as a lower level filter, so that it is always applied and vit's filter applies over the report's filter).
I'm willing to help develop a fix for this.

**Comment by thehunmonkgroup** [comment]
I'm not sure what you're talking about. VIT 2.x reads the report config from TaskWarrior, and applies the correct filters to all reports, that's how it's designed.

If there's a specific report that is not being displayed correctly, please provide the report name and all associated TaskWarrior config for the report so I can investigate.

**Comment by nfraprado** [comment]
Well, actually none of the reports are having their filter loaded, which is why I thought this wasn't implemented. For example, I have in my taskrc the following custom filter for next:
`report.next.filter = status:pending type:next +UNBLOCKED`.
This filter works fine in standalone taskwarrior and even vit 1.x but in vit 2.x the next report shows all tasks with no filter whatsoever. I can tell the taskrc is being used because as I change the report in vit2.x, the columns in each report change, though all tasks are always showed since there is no filter in any of them.

**Comment by thehunmonkgroup** [comment]
Please include the output of:

```
task _show | grep report.next
```

**Comment by nfraprado** [comment]
Sorry, wasn't sure what other informations to include.
`$ task _show | grep report.next`
```report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
report.next.description=Most urgent tasks
report.next.filter=status:pending type:next +UNBLOCKED
report.next.labels=ID,Active,Age,Deps,P,Project,Tag,Recur,S,Due,Until,Description,Urg
report.next.sort=urgency-
```

**Comment by thehunmonkgroup** [comment]
If you remove your customization of the next report in ```.taskrc```, does the report output correctly in VIT?

**Comment by nfraprado** [comment]
Just tried it out and no, it doesn't, the problem persists. Just to be clear this also happens to my other custom reports. In all of them the labels are shown correctly, only the filter isn't set for some reason.

**Comment by thehunmonkgroup** [comment]
Yes, I understand that. I'm focusing on that report for now for simplicity.

At this point I'm stumped -- VIT 2.x is properly filtering all reports in my local installation, and I've received no other reports of this issue. I'm pretty sure if this was a widespread issue, more reports would be coming in.

Next step would probably be an environment report:

1. Python version?
2. Output of ```pip freeze```
3. OS type/version?
4. Any other customization stuff you can think of related to your shell, Python, or TaskWarrior?

**Comment by scottkosty** [comment]
Perhaps a minimal example `.taskrc` and `.vitrc` would help?

**Comment by nfraprado** [comment]
Actually, I seem to have found the culprit. Removing the current active context definition from my taskrc fixed it. So, it seems that the context filter is overloading the report filter, since only the context filter is being used instead of a combination of both filters. I tried exploring the code a bit but would need more time to get my bearings and fix it, so I'm just reporting this to you in case you know what might be causing this.

**Comment by thehunmonkgroup** [comment]
Hm. That doesn't make any sense. VIT 2.x doesn't do anything with context, that is entirely controlled by TaskWarrior, I believe by reading the context from the ```.taskrc``` setting.

To retrieve data for a report, VIT 2.x calls the task binary's export function, and passes it the filters for the report in question. Again, what comes back is entirely controlled by TaskWarrior, which, if context is set, would apply the context filters and the export filters. None of this happens outside the ```task``` binary.

I cannot reproduce your issue. I can set a context, (or set no context) with the ```next``` report in my local installation, and VIT correctly displays the filtered data in both cases.

**Comment by thehunmonkgroup** [comment]
What version of TaskWarrior are you using?

**Comment by nfraprado** [comment]
Hm, that's strange. I read `context_filters` on line 848 of application.py and was sure that it was passing the context filter to taskwarrior and somehow overloading the report's filter.
My setup is:
Distro: ArchLinux
Kernel: 5.2.9-arch1-1-ARCH
TaskWarrior: 2.5.1
Python: 3.7.4
Vit: 2.0.0b2
Pip freeze:
```
pytz==2019.2
six==1.12.0
tasklib==1.2.1
tzlocal==2.0.0
urwid==2.0.1
vit==2.0.0b2
```
(This is from a virtualenv, also tried outside it and the problem stays the same)

**Comment by thehunmonkgroup** [comment]
Well, this is an example of me forgetting my own code ;)

You're right, VIT 2.x does load the context filters from TaskWarrior and combine them with the report filters and any custom filters the user applies to the report.

However, the combining is additive and quite straightforward. I still cannot reproduce the issue you describe.

Perhaps if you apply this debugging patch you can discover what's going on in your case:

```diff
diff --git a/vit/task.py b/vit/task.py
index e51bb03..a375dd5 100644
--- a/vit/task.py
+++ b/vit/task.py
@@ -28,6 +28,15 @@ class TaskListModel(object):
         active_report = self.active_report()
         filters = active_report['filter'] if 'filter' in active_report else []
         all_filters = filters + extra_filters
+        import debug
+        debug.file('#####################')
+        debug.file('Filters')
+        debug.file(filters)
+        debug.file('Extra filters')
+        debug.file(extra_filters)
+        debug.file('All filters')
+        debug.file(all_filters)
+        debug.file('#####################')
         self.tasks = self.tw.tasks.filter(*all_filters) if len(all_filters) > 0 else self.tw.tasks.all()
 
     def get_task(self, uuid):
```

That will output debugging info to ```/tmp/vit-debug.log``` (in master branch, or ```/tmp/test``` in beta2) *after* you quit the VIT application.

Let me know what you find, if you can get me info to reproduce the issue, we'll fix it!

**Comment by nfraprado** [comment]
I'm sorry, but I just solved the problem and it was totally my fault. In my taskrc I had the following context defined: `context.uni:+@uni or (-@rep -@sp)`. It turns out that when vit invoked tasklib with both the report filter (for the next report:`status:pending type:next +UNBLOCKED`) and the context filter, the `or` made the filter be either `status:pending type:next +UNBLOCKED +@uni` or `(-@rep -@sp)`, which is obviously wrong. So in the end the problem was due to a misplaced parenthesis (should have been `(+@uni or -@rep -@sp)`) that I never noticed because in taskwarrior the context and the report filter are applied separately, while in vit both are applied together as filters. Anyway, just thought I would explain the source of the problem. Sorry again for wasting your time with a mistake of mine. I'll close this issue now.

**Comment by thehunmonkgroup** [comment]
Ah, thanks for reporting your solution, it did in fact expose an edge case bug.

Users should not have to worry about grouping between filter types as you have, as they can be properly grouped by VIT when building the export command, by surrounding each filter type (context, report, custom user filters) with parentheses.

https://github.com/scottkosty/vit/commit/442cd155789eaf2bbfc2e90ba54fcbd81c6a65e4 fixes this shortcoming.
