### ISSUE TITLE
vit 2.x: passing negative filters through to task don't work

### ISSUE THREAD

**Issue by dustymabe** [vit-project/vit#206]
If I want to disable/enable viewing certain tags when I run vit I used to be able (vit 1.x) to pass through `+tag` `-tag`. In 2.x the argument parsing will give an error for `-tag` arguements that are not registered arguments for vit (i.e. it won't pass them through to task).

- `vit next +tag`
    - works as expected
- `vit next -tag`
    - error: `vit: error: no such option: -t`
    - workaround by explicitly turning off argument parsing: `vit oldest -- -tag`

**Comment by thehunmonkgroup** [comment]
I was using Python's older ```optparse``` module, which doesn't allow a clean way to ignore unknown args.

Switching to the newer ```argparse``` module seems to have fixed the issue, try out latest master to see if that works for you.

**Comment by dustymabe** [comment]
thanks! I'll try it out soon
