### ISSUE TITLE
vit 2.x: enable passing config file via environment variable

### ISSUE THREAD

**Issue by dustymabe** [vit-project/vit#207]
It would be nice if we could specify the config file location via an environment variable:

```
export VIT_CONFIG_FILE=/path/to/config
/usr/bin/vit
```

**Comment by thehunmonkgroup** [comment]
See https://github.com/scottkosty/vit/blob/2.x/CUSTOMIZE.md#configuration

**Comment by dustymabe** [comment]
> See https://github.com/scottkosty/vit/blob/2.x/CUSTOMIZE.md#configuration

Thanks @thehunmonkgroup! For those reading along at home it looks like we should use the `VIT_DIR` environment variable and set it to the directory that houses the `config.ini`
