### ISSUE TITLE
highlight does not move with urwid-1.3.1

### ISSUE THREAD

**Issue by akadaedalus** [vit-project/vit#218]
I was able to make this work with urwid-2.0.1, so mostly informational.  I had to unmask it in my Gentoo installation.

When I was using the keys to move between rows, the blue highlight stayed at the top.  By hitting enter, or going to the next page, I could finally see it was selecting different tasks but the highlight never moved.  Upgrading urwid solved this.

**Comment by thehunmonkgroup** [comment]
Thanks for this report. As a remedy going forward, I've forced minimum versions of all required packages, which as of the fix, are:

```
pytz>=2019.3
tasklib>=1.3.0
tzlocal>=2.0.0
urwid>=2.1.0
```
