### ISSUE TITLE
can't get my own reports to work

### ISSUE THREAD

**Issue by mrVanDalo** [vit-project/vit#223]
When I use my own report : 
```
report.todo.columns=id,project,tags,description
report.todo.description=Show short active Tasks
report.todo.filter=(+ACTIVE or +TODAY or +OVERDUE or (+READY and +SCHEDULED)) status:pending
report.todo.labels=Id,Project,Tags,Description
report.todo.sort=urgency-
```

in vit : `vit todo`
I get this error :
```
VIT fatal error: (converted from warning) Use of uninitialized value $prev_id in concatenation (.) or string at /nix/store/nnjsamhnzdgkn36g09ncpbj0djwfdpl0-vit-1.3/bin/.vit-wrapped line 2142, <IN> line 2.
```

Using this report with `task` always worked.

**Comment by scottkosty** [comment]
Thanks for the report. It looks like you're using VIT 1.3. Can you try with either VIT 2.0, which is the newest release of VIT, or with the 2.x branch?

**Comment by mrVanDalo** [comment]
You are right, there is a newer version in the unstable-channel. Thank you, will try harder  in the future to check that first.

**Comment by scottkosty** [comment]
No problem at all. We look forward to your feedback on 2.x!
