### ISSUE TITLE
Unable to show all markers

### ISSUE THREAD

**Issue by vortexnix** [vit-project/vit#226]
These are the settings in `~/.vit/config.ini` for `[marker]` section

```
enabled = True
columns = all
header_label = Marker
require_color = False
include_subprojects = False
due.today.label = (DT)
tag.remindme.label = (R)
```

The `Marker` column is shown. But it only shows marker (P) for project and nothing else. There are no color related settings in `~/.taskrc`. Not sure what I am doing wrong here.
```
vit --version
2.0.0

task --version
2.5.1
```

**Comment by thehunmonkgroup** [comment]
My guess is you're misunderstanding the purpose of markers. Markers are only displayed when the relevant column they would be coloring is not displayed in the report, otherwise the column itself is colored.

See https://github.com/scottkosty/vit/blob/2.x/COLOR.md

**Comment by vortexnix** [comment]
Okay. Thanks. In my humble opinion such a condition limits the use case for the markers. For example, I use row coloring with `task next report` to quickly identify the task that are due today. Then the `Due` column shows which task is due first (1h, 5h etc.) and I can work on the task that is due first. With `vit 2.x`, if I use marker `(DT)` to identify the tasks that are due today but then the `Due` column is suppressed. I have no way of knowing which task is due first by simply looking at the report. The more helpful implementation at least for me would be to allow markers (with or without colors) to show independently of the columns displayed in the report. Columns simply offer more information than text indicators. This way markers can be perfect replacement of row coloring. Users can customize what columns and markers to be displayed at the same time.

**Comment by thehunmonkgroup** [comment]
I'm not sure what you mean. If you have a Due column in your report, it will be properly colored based on your ```.taskrc``` configuration for due/overdue/etc. The purpose of markers is to supply color information for a task when a report doesn't include a column.

**Comment by thehunmonkgroup** [comment]
The attached image illustrates what I'm talking about.
![task-coloring-markers](https://user-images.githubusercontent.com/43772/75612570-96a4b080-5ad9-11ea-8795-e4348ccc45ac.png)

**Comment by vortexnix** [comment]
Okay. I understand. I thought to use marker as replacement for row coloring, but may be not. It is acceptable when the column itself is not offering any additional information. In your example, The text indicator (BG) indicates whether blocking or not. However, take for example of Due column. Consider the screenshot from vit 1.x below:
![taskview3](https://user-images.githubusercontent.com/13627703/75613036-34f33f00-5af7-11ea-926b-c07c5cb7c4c0.png)
I will complete task 49 first followed by 45,51,43,46,47 in the order of due time. 
Now if the markers enabled in vit 2.x, the screenshot looks like:
![vitview3](https://user-images.githubusercontent.com/13627703/75613072-987d6c80-5af7-11ea-8dee-d59f34f6a7b8.png)
Now, I have no way to know which task is  due first since I need to disable Due column to enable corresponding marker. In this case I guess it is not advisable to use markers. They are useful when indicating a boolean value.

**Comment by thehunmonkgroup** [comment]
I'm not sure you do understand. Look at the following image. The colors for due and overdue are *there*, in the Due column itself. You don't need markers for that:
![due-overdue-coloring](https://user-images.githubusercontent.com/43772/75613808-b0002980-5ae6-11ea-83a3-6a869579ba02.png)

Please re-read https://github.com/scottkosty/vit/blob/2.x/COLOR.md -- it explains the tradeoffs that were made with this new color approach, which I believe is superior overall.

You are, of course, welcome to continue using Vit 1.x if you prefer that coloring approach. No further development is planned for that branch.

**Comment by vortexnix** [comment]
Thanks. That is sort of my point. Vit 2.x does provide markers for a columns like "due" that can be colored directly and using the marker does not offer any additional advantage. I am aware that markers are useful when the report does not have that specific column. I would rather include that column instead. At least for my cases, I could not find any use for markers. I really wish vit 2.x could support row based coloring from taskrc. Personally, I find it more elegant in terms of visualization and the background color of the columns also remain consistent.

**Comment by thehunmonkgroup** [comment]
> I would rather include that column instead

I'm afraid I don't understand what you mean by that.

>  I really wish vit 2.x could support row based coloring from taskrc

You don't have to wish -- Vit is open source software, and you are free to fork and modify it as you like. If your code is clean, I *might* consider merging it into the project. I will say, however, that the work done around color management was some of the most difficult in the rewrite, and for me, supporting two different coloring schemes wasn't worth it -- I personally hate the default ```task``` coloring approach -- it's not only loud, but it also results in the loss of visual cues in more complicated cases, and the color merging is confusing IMO.

One last point to make here: if part of the issue is that the coloring is too subtle for you, you do have full control over the color output for due/overdue. Something like this:
```ini
  color.due=black on brown
  color.overdue=white on red
```
Which gives some pretty obvious visual indicators, no markers necessary:
![stronger-due-colors](https://user-images.githubusercontent.com/43772/75616798-cb7d2b80-5b0a-11ea-91f2-47056a94e125.png)

**Comment by vortexnix** [comment]
> You don't have to wish -- Vit is open source software, and you are free to fork and modify it as you like. 

I can give it a try. I am afraid my coding skills are not good enough to implement something as complex as row-coloring with no knowledge of curses module or code structure. That is why I am sincerely grateful to developers like you who put in the time and effort to build such great open source projects. 

I use taskwarrior synced with google calendar (there is another open source project for syncing to google calendar called `taskw_gcal_sync`) for day to day task management. My use case/tasks are fairly trivial and the task coloring approach seem to work for them. One glance of `task next` gives me a good idea of what needs to done next since rows are uniformly colored. Regarding color noise, I sincerely think task coloring can be customized to subtle colors on a 256 color palette.  I do also agree with you. A single unified row color might not work for complicated cases. I presumed that markers would be the solution for it such that most of the report will be no colors and markers will be colored to highlight relevant attributes of the task. It turns out the purpose of markers is entirely different.
