### ISSUE TITLE
Display "due.formatted" column in next report

### ISSUE THREAD

**Issue by vortexnix** [vit-project/vit#227]
I am trying to customize the next report of the taskwarrior by adding follwing to `~/.taskrc`
```
report.next.columns=id,due.formatted,description.count,tags,recur
report.next.labels=ID,Duef,Description,Tags,Recur
```
All the columns are displayed properly when using `task next` in terminal. However, with `vit 2.0.0`, the `Duef` column is not displayed. The column gets displayed when using `due.relative` instead of `due.formatted`. Looks like the date enabled `due.formatted` is not supported at the moment. It will be very helpful if it gets supported.

**Comment by thehunmonkgroup** [comment]
Tested the config you provide above, and it's working fine in my installation. ```due``` and ```due.formatted``` both output the same format.

If I had to guess, you've either added a custom formatter which is overriding the default, or there's not actually any data in the due column for the tasks in the report, so it's not outputting anything.

**Comment by vortexnix** [comment]
But the default `due` format should display the date. 
![dueformatted](https://user-images.githubusercontent.com/13627703/75613361-b8625f80-5afa-11ea-879a-2c317d6bcf00.png)
The default due in `vit 2.x` seems to be `due.relative`. With this setting:
```
report.next.columns=id,due,description.count,tags,recur
report.next.labels=ID,Due,Description,Tags,Recur
```
This is what I get in vit 1.x
![due1](https://user-images.githubusercontent.com/13627703/75613364-c2845e00-5afa-11ea-85a7-8f936999054b.png)
And for some reason, I cant get default due to display in vit 2.x:
![due2](https://user-images.githubusercontent.com/13627703/75613386-09725380-5afb-11ea-80ca-c840eb6ddb5b.png)

**Comment by thehunmonkgroup** [comment]
I suspect if you run ```task _show | grep ^dateformat``` you'll get output like this:
```
dateformat=Y-M-D
dateformat.annotation=
dateformat.edit=Y-M-D H:N:S
dateformat.holiday=YMD
dateformat.info=Y-M-D H:N:S
dateformat.report=
```

Vit uses the ```dateformat.report``` and ```dateformat.annotation``` settings for formatting dates in reports.

https://github.com/scottkosty/vit/commit/e8f30dcb3afffdd4ec0b071fabd8ceb4ec3eac97 fixes the bug, by falling back to the ```dateformat``` setting if the others are not set.

Until the next release, you can work around this issue by setting ```dateformat.report``` and ```dateformat.annotation```  in ```.taskrc``` to your preferred values.

**Comment by vortexnix** [comment]
Cool. Thank you. Adding it in `~/.taskrc ` resolved the issue
```
dateformat.report=Y-M-D 
dateformat.annotation=Y-M-D 
```
