### ISSUE TITLE
Blank screen when no .taskrc file exist

### ISSUE THREAD

**Issue by etanot** [vit-project/vit#229]
### Description
I've recently installed `vit` in my Debian system; and just after installation, I run `vit` command which lead to a blank screen, like this

![vit](https://user-images.githubusercontent.com/28824347/76013543-f81cb300-5f0f-11ea-956a-8202820c1be6.png)

in which I cannot perform a single operation; I've to forcefully kill terminal session. I little dug around, and found out that this happens because ~/.taskrc file doesn't exist. And I noticed one more thing, when I've no task in list, I get this error message,

```
Fatal error: default.command ("next") must print an "ID" column
```

Sorry, if these are expected behavior. If so, shouldn't we handle these cases properly? means prompt users to create ~/.taskrc file, just like `taskwarrior` does or at least show proper error message instead of a blank screen.

### Steps to reproduce
**Part 1**:
- Install a fresh copy of `vit` (make sure no ~/.taskrc file and ~/.task folder exist).
- Run `vit` command from terminal (probably you'll get a blank screen).

**Part 2**:
- Run `task` command to create a ~/.taskrc file and ~/.task folder (make sure you didn't add a task, so running a simple `task` would be fine).
- Now run `vit` command, again (this time you should get **fatal error** error message).

### Actual Output
A blank screen is popped-up, in which no operation is performed; I've to forcefully kill terminal session.

![vit](https://user-images.githubusercontent.com/28824347/76013543-f81cb300-5f0f-11ea-956a-8202820c1be6.png)

### Expected Output
If ~/.taskrc doesn't exist, pop a prompt to create a new one.

**Comment by thehunmonkgroup** [comment]
This sounds like you've got VIT 1.3 installed. Try installing the 2.x version.

VIT runs successfully on top of a properly configured TaskWarrior, I don't think it's VIT's responsibility to handle things at that layer.

**Comment by etanot** [comment]
> This sounds like you've got VIT 1.3 installed.

Yeah, you're right.

```
$ vit --version
1.3.beta1
```

> Try installing the 2.x version.

I will; sorry for not tried to reproduce this behavior on latest version.


> VIT runs successfully on top of a properly configured TaskWarrior, I
don't think it's VIT's responsibility to handle things at that layer.

But at least we can show proper error message, instead of popping-up
blank screen, on which user cannot perform any operation.

**Comment by thehunmonkgroup** [comment]
> But at least we can show proper error message, instead of popping-up blank screen, on which user cannot perform any operation.

You'll need to see how VIT 2.x acts in that situation, I'm not sure what will happen.

**Comment by thehunmonkgroup** [comment]
I don't think anything needs to be done here, closing for now, please re-open if there's any new information.
