### ISSUE TITLE
Feature request: add command to ex "!rw task <id>"

### ISSUE THREAD

**Issue by ipwnponies** [vit-project/vit#232]
The hotkey `t` currently enters ex mode with the static string "!rw task".

https://github.com/scottkosty/vit/blob/bf4cb069228e12b26e436b120fb9938a2b6a1531/vit/application.py#L609-L610

This appears to be an escape hatch to proxy to `task` cli.
Personally, I haven't found this useful: if I'm going to use the cli, I'm wanting to leverage the shell's features (autocomplete, shell scripting).

A more useful feature would be to enter ex mode with "!rw task <task_id>" where `task_id` is the focused task.

A real use case to serve as an example is using `task <id> done <annotation>`.
Occasionally, I'd like to complete a task and annotate.
`vit` requires reversing the order, annotating first and then done.
Which is mildly annoying/friction.

**Comment by ipwnponies** [comment]
I've been playing around with this change to the function:
```python
def activate_command_bar_ex_read_wait_task(self):
    uuid, _ = self.get_focused_task()
    task_id = self.model.task_id(uuid)
    self.activate_command_bar('ex', ':', {}, edit_text='!rw task {} '.format(task_id))
```

**Comment by thehunmonkgroup** [comment]
I'm not inclined to make this change. It's already doable via a custom keybinding:
```dosini
t = :!wr task {TASK_UUID}<Space>
```

I *might* be willing to add ```{TASK_ID}``` as another token, but ```{TASK_UUID}``` works just fine.

**Comment by ipwnponies** [comment]
D'oh, my bad for not reading the documentation more closely! Yes, the solution you've presented perfectly fulfills my ask.

To leave a complete trail, this was [documented in the sample config][1] for setting up custom macros.

[1]: https://github.com/scottkosty/vit/blob/7200949214362139e8073b6ca1a58cc756b2ebd0/vit/config/config.sample.ini#L198-L205
