### ISSUE TITLE
can vit (be made to) run arbitrary commands?

### ISSUE THREAD

**Issue by ahillio** [vit-project/vit#236]
I've been using [tasknote](https://github.com/mikebobroski/tasknote) and loving it, using vit and loving it, but sadly these two things are separate right now.  Tasknote let's me keep individual text files associated with individual tasks and it'd be so awesome to be able to easily open those files from the vit interface.

I'd love to be able to just scroll through vit's awesome interface and on any task do something like `:tnt` (or something similarly easy, better would be a keybinding) to invoke the tasknote.sh script on that task (it'd need to pass the task id as an argument to that script).

Is there a way to run arbitrary commands from within vit?  Like is it possible to configure something in the vit config file or is there a plugin system or any other mechanism for doing such things?

**Comment by scottkosty** [comment]
Take a look at https://github.com/scottkosty/vit/blob/2.x/vit/config/config.sample.ini. Scroll to the bottom, or search for "OneNote". That should give you an idea of how to customize to use tasknote.

**Comment by ahillio** [comment]
Oh that's so good :)

Is there a way to see all the existing config variables?  I tried `z = !wr echo "{TASK_DESCRIPTION}" > sweetness.txt` to see what could be done using this mechanism but vit doesn't like that.

Also what's the `!wr` part?

**Comment by ahillio** [comment]
Also I tried making the keybinding be `<Shift><Enter>` but the shift didn't make a difference, the action bound to just the `<Enter>` key was the action invoked.  Is there a way to keep `<Enter>` bound to the current/default command but have `<Shift><Enter>` (pressed simultaneously) bound to a different action?

**Comment by thehunmonkgroup** [comment]
https://github.com/scottkosty/vit/blob/2.x/vit/config/config.sample.ini and the various markdown files in the repo root contain all the documentation we have, I suggest studying those, it will save all of us a lot of time ;)

I'm not even sure ```<Shift><Enter>``` is a valid key combination. At any rate, VIT accepts any keypress recognized by Urwid.

**Comment by KingOfSpades** [comment]
For future readers. The trick here is to add the script you want to run to your `$PATH`. For example, lets make a script that sets a task. I added it to the FAQ as an example https://github.com/vit-project/vit/pull/377
