### ISSUE TITLE
Vit crashes when report has project column but no sort

### ISSUE THREAD

**Issue by nfraprado** [vit-project/vit#237]
When a report is configured to have `project` as one of the columns but no `sort` is defined for the report, vit crashes with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/vit", line 11, in <module>
    load_entry_point('vit', 'console_scripts', 'vit')()
  File "/home/nfraprado/code/contrib/vit/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/nfraprado/code/contrib/vit/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/home/nfraprado/code/contrib/vit/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/home/nfraprado/code/contrib/vit/vit/config_parser.py", line 342, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/home/nfraprado/code/contrib/vit/vit/config_parser.py", line 346, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/home/nfraprado/code/contrib/vit/vit/config_parser.py", line 353, in has_primary_project_ascending_sort
    primary_sort = report['sort'][0]
KeyError: 'sort'
```

To reproduce, simply generate a dummy install and add the following:
```
report.test.columns=id,project
report.test.labels=ID,Project
```
If a sort, even if empty, is added, the error is solved:
```
report.test.sort=
```

**Comment by scottkosty** [comment]
Thanks for your report and for the pull request! @thehunmonkgroup will know better than I, but in the hopes of saving him time, instead of using a "try" can't we just check whether the "report" object has an element "sort" (and that that element is non-empty or whatever else is needed)? I'm not experienced in Python, so perhaps try is actually the natural way?

**Comment by nfraprado** [comment]
From what I understand of python, using try is actually the natural way, following the EAFP principle: "Easier to ask for forgiveness than permission" (https://docs.python.org/3.8/glossary.html).

But if @thehunmonkgroup would rather do the way you suggested, I'm okay with that too and I can change it no problem.

**Comment by thehunmonkgroup** [comment]
It's always seemed weird to me, but AFAIK, the ```try/catch``` approach is the accepted convention in Python.

**Comment by scottkosty** [comment]
Good to know! Thanks for the explanations. I will keep EAFP in mind.
