### ISSUE TITLE
Bind ? to :help

### ISSUE THREAD

**Issue by tbm** [vit-project/vit#241]
Would it make sense to bind `?` to `:help` in the default config?  Pressing `?` is more obvious for a new user than typing `:h` or `:help`.

vit feels similar to mutt to me and there pressing '?' works.

**Comment by scottkosty** [comment]
Indeed, VIT is partly inspired by mutt. In some sense VIT is closer to mutt than Vim, since navigating emails is closer to navigating tasks than writing a document is.

However, `?` is a natural candidate for searching backwards, which would be consistent with a lot of programs, including Vim. In mutt I always found it unintuitive to do `<Esc> + /` to search backwards.

**Comment by tbm** [comment]
You're making a good point.

Feel free to close this issue.

**Comment by scottkosty** [comment]
Let's see what @thehunmonkgroup thinks. I'm leaning towards supporting closing it, but perhaps other users do find `<Esc> + /` to be intuitive for searching backwards? I've only noticed myself complaining about it :)

**Comment by tbm** [comment]
Arguably, those who care enough about reverse-search can probably figure out how to override the `?` binding whereas those new to VIT can't as easily figure out that they have to type `:help`.  So from that POV having `?` as help by default seems better to me.  But clearly I'm biased. ;)

**Comment by scottkosty** [comment]
That's a good argument :). I'm still not convinced though. We do have ":help" listed on the README.md page which I hope a user would go to if they were feeling lost. To be clear, I think I would support your proposed change if `?` were not so commonly used in a lot of applications for searching backwards.

**Comment by thehunmonkgroup** [comment]
I think we're a little too far into the history of VIT to be monkeying with default key mappings. Doing that would break things for all existing users, unless we found some way to only use that for new installs, which feels clunky to me.

Your arguments are certainly valid, and if this was earlier in this software's lifecycle, I'd probably go for it.

If we're thinking creatively, I'd go more for an intro screen type of thing, that displays the first time a user loads VIT. On that screen we could provide a quick high-level overview, including how to get help.

**Comment by tbm** [comment]
> I think we're a little too far into the history of VIT to be monkeying with default key mappings. Doing that would break things for all existing users

Sorry if this question doesn't make sense, but why would that break things for existing users?  Currently `?` is not mapped by default, so users who use `?` must have mapped it to something via a config option.  If this is true, a *default* for `?` wouldn't impact existing users since they explicitly changed the setting in their config.

Again, I'm a new user and haven't looked at VIT in detail, so maybe I'm wrong.

> I'd go more for an intro screen type of thing, that displays the first time a user loads VIT

I was going to suggest at least mentioning `:help`: in the `--help`` text but I see that's there already.

Anyway, you two know best what makes sense.  If you want to implement something, great. If you want to close this issue, that's ok with me too.

Thanks for the responses.

**Comment by thehunmonkgroup** [comment]
> Sorry if this question doesn't make sense, but why would that break things for existing users? Currently ? is not mapped by default

I beg to differ :)

Have a look here: https://github.com/scottkosty/vit/blob/2.x/vit/keybinding/vi.ini

And you'll see...

```? = {ACTION_COMMAND_BAR_SEARCH_REVERSE}```

I took a quick look at adding a reference to ```:help``` as part of the user feedback after creating a default ```config.ini```, but it just seemed out of place.

If we want to discuss some kind of intro thing, we can do it in another issue.

**Comment by tbm** [comment]
> I beg to differ :)

> Have a look here: https://github.com/scottkosty/vit/blob/2.x/vit/keybinding/vi.ini

Sorry, for some reason I completely missed this!

But now this whole conversation makes much more sense.  For you I requested a CHANGE of behaviour whereas I just asked for a  binding of the unused `?`.

Thanks for your patience.  I agree with closing this issue.
