### ISSUE TITLE
Very narrow description column

### ISSUE THREAD

**Issue by gaalcaras** [vit-project/vit#245]
Using the latest version of vit's master branch (on ArchLinux via the AUR package), I get a really narrow description column inside my terminal.

![Example](https://user-images.githubusercontent.com/6551953/85278913-eabb1280-b485-11ea-9bb0-209598fbbff6.png)

Strings are truncated at the 21th column: `Envoyer plan de thès...` . Results are the same in termite and xterm.

Any ideas on how to solve this would be much appreciated.

**Comment by thehunmonkgroup** [comment]
I don't understand ArchLinux's packaging system, and would recommend you install the master branch via https://github.com/scottkosty/vit/blob/2.x/DEVELOPMENT.md

**Comment by nblock** [comment]
> I don't understand ArchLinux's packaging system, and would recommend you install the master branch via https://github.com/scottkosty/vit/blob/2.x/DEVELOPMENT.md

(maintainer of the mentioned Arch package here). When the package is built on an Arch system, the most recent Git commit is checked out and built, it should not differ from a manual installation. @gaalcaras Can you reproduce this issue with a manual installation, via virtualenv for example?

**Comment by thehunmonkgroup** [comment]
I'm running latest master on my local dev box, and cannot reproduce this problem.

If you can provide a specific test case then I may be able to help more. You can use https://github.com/scottkosty/vit/blob/2.x/scripts/generate-dummy-install.sh as a starting place to generate the test case.

**Comment by gaalcaras** [comment]
Thanks to you two for your feedback. I will compile from source and try to reproduce the problem as soon as I have the time.

**Comment by gaalcaras** [comment]
This was actually easier than I thought. Setting up a dummy install revealed that the problem was with my `taskrc` config. I narrowed it down to the formatter `description.truncated_count` in my custom reports (see [Taskwarrior docs](https://taskwarrior.org/docs/commands/columns.html)).

The reason I didn't pick it up first is that with`task`, the name of the task is not truncated but the lines with the annotations are "folded" and the number of folded lines appears between brackets.

With `task`, just `description`:

![With task](https://user-images.githubusercontent.com/6551953/85336310-b293ee00-b4de-11ea-9edb-01fae313e8aa.png)

With `task`, with `description.truncated_count`:
![With task, truncated_count](https://user-images.githubusercontent.com/6551953/85336069-5630ce80-b4de-11ea-8fa2-e8734e30266c.png)

In `vit`, with `description.truncated_count`:
![In vit](https://user-images.githubusercontent.com/6551953/85336131-6a74cb80-b4de-11ea-8e76-66fce8a65014.png)

Anyway, setting up another report without `description.truncated_count` should do the trick in `vit` for now.

I like having just one line per task though. Is there a way to "fold" annotations in the same way with vit? Or could vit possibly support the `truncated` and `truncated_count` formats in the same way `task` does?

**Comment by nfraprado** [comment]
In my configuration I use `description.count` for having only one line per task, with the number of annotations between brackets. I think you're actually mixing the effect of `truncated` and `count` by using `truncated_count`. There are a couple examples here: https://taskwarrior.org/docs/report.html

**Comment by thehunmonkgroup** [comment]
> I like having just one line per task though. Is there a way to "fold" annotations in the same way with vit? Or could vit possibly support the truncated and truncated_count formats in the same way task does?

These should be split and filed as separate issues if you want to pursue them.

**Comment by gaalcaras** [comment]
> In my configuration I use `description.count` for having only one line per task, with the number of annotations between brackets. I think you're actually mixing the effect of `truncated` and `count` by using `truncated_count`.

You're absolutely right. I'll be using `count` instead!
