### ISSUE TITLE
upon adding new task, highlight it

### ISSUE THREAD

**Issue by ahillio** [vit-project/vit#246]
Currently when vit adds a new task it then highlights the task at the top of the list.  So if I want to go and do something on the task I just created, for example starting the timer, I have to first navigate to it.  It would be great if there was a config setting to automatically highlight the task after it's created.

I've looked through the example config and don't see any options for this.  Is there one?  Can this be achieved somehow?

**Comment by ahillio** [comment]
From https://github.com/scottkosty/vit/issues/209 it sounds like what I'm hoping for can't be achieved currently....?

**Comment by thehunmonkgroup** [comment]
No, it cannot. I'm resistant to hard code this feature when a more generalized solution is under consideration, so it's doubtful this will be addressed any time soon.

**Comment by ahillio** [comment]
Thanks for clarifying that!
