### ISSUE TITLE
vit freezes on startup if there is no taskrc file present

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#255]
This is problematic upon first execution, if user hasn't yet created a _.taskrc_ config file (or had it created by _task_), he may just conclude that vit just doesn't work and abandon altogether.

On startup, if no .taskrc file is available, _task_ then generates one, upon user confirmation.
_Would you like a sample /path/.taskrc created, so Taskwarrior can proceed? (yes/no)_

Reproduce: execute _TASKRC=/path/.dummytaskrc vit_  (you can also instead rename old .taskrc)
Vit probably expects a non-interactive/blocking reply.

A solution could be to give user control if rc file isn't found, and react accordingly when _task_ returns (check existence of file/return code)
Alternatively, have _vit_ create a dummy rc file itself (with or without confirmation), but it should been best left to _task_.

**Comment by thehunmonkgroup** [comment]
I think probably the cleanest way to handle this is to exit VIT with a sensible error message. VIT does depend on TaskWarrior after all, so bailing if it's not properly configured seems to be a reasonable approach.

Thoughts?

**Comment by fdela** [comment]
> I think probably the cleanest way to handle this is to exit VIT with a sensible error message. VIT does depend on TaskWarrior after all, so bailing if it's not properly configured seems to be a reasonable approach.
> 
> Thoughts?

Makes sense.
The most important is to clearly tell the user what the problem is and how to address it (i.e. by running _task_ once to generate the config file)
