### ISSUE TITLE
Non-pending blocking tasks should not appear in reports as dependencies

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#256]
Say you have task 1 blocking task 2
Vit shows among other:
|       |  ID | Deps | Virtual tags
|-----|----|------| ---
|(BG)| 1   |         | BLOCKING PENDING READY UNBLOCKED
|       | 2   |   1    | BLOCKED PENDING

If you now mark 1 as done, you get
|       |  ID | Deps | Virtual tags
|-----|----|------| ---
|       | 2   |   _uuidOld1_ | PENDING READY UNBLOCKED

The completed task 1 shouldn't appear in the reports (list, next, etc) as dependency of task 2, to be consistent with TaskWarrior: finished blocking tasks aren't really blocking anymore. It doesn't appear in task 2 info anymore anyway.

Note _uuidOld1_ appears in task 2 export { "id":2,"depends":"_uuidOld1_",... } in all cases, whether task 1 is pending or not, so filtering should be done on displayed dependencies to only include those with pending status, and not completed/deleted/...

**Comment by thehunmonkgroup** [comment]
In order to look at this, I'll need a test case. You can use https://github.com/scottkosty/vit/blob/2.x/scripts/generate-dummy-install.sh as a starting point, and configure and post a script that sets up a TaskWarrior instance with the necessary data for me to see and work with the problem.

**Comment by fdela** [comment]
You can spot this issue with reports showing the _depends_ column. In attached test case, you can see it happen with the _long_, _next_, _overdue_ and _unblocked_ reports.

[generate-non-pending-deps.sh.txt](https://github.com/vit-project/vit/files/4990373/generate-non-pending-deps.sh.txt)

**Comment by thehunmonkgroup** [comment]
I'm *pretty* sure I got this fixed, but some testing to make sure it works, and that I didn't break anything, would help!
