### ISSUE TITLE
Allow overriding task data location in config.ini

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#257]
Currently, taskrc file location is overridable in vit `config.ini` file (and indirectly via TASKRC envvar)

``` 
[taskwarrior]

# Full path to the Taskwarrior configuration file. Tilde will be expanded to the user's home directory.
# NOTE: This setting is overridden by the TASKRC environment variable.
#taskrc = ~/.taskrc
```
For consistency, a similar mechanism should exist for task data directory (TASKDATA environment variable).

See [_CONFIGURATION FILE AND OVERRIDE OPTIONS_ section in task(1) manpage](https://manpages.ubuntu.com/manpages/focal/en/man1/task.1.html#configuration%20file%20and%20override%20options) for details.

**Comment by thehunmonkgroup** [comment]
I don't like the idea of providing a bunch of extra config options that map to TaskWarrior ones, there are too many.

What I *might* be open to is adding a single new config option in the ```[taskwarrior]``` section, something like ```default_args```. If set, those would be passed to every TaskWarrior command.

Thoughts?

**Comment by fdela** [comment]
Yes, a `default_args` config option would do, whose contents is passed to every taskwarrior command.
Care should be taken to respect precedence of options, so they are applied by increasing precedence: `config.ini` -> environment variable -> command line option

Note that there could be 2 locations for tw config file in `config.ini`: `taskrc` and `default_args` (_rc_:...).
In this case, I suggest having `default_args` a lower priority than `taskrc`, so the former would be applied first on the constructed command line.

Alternatively, one could get rid of `taskrc` config option altogether and set default value of `default_args` to `#default_args = rc:~/.taskrc`

**Comment by thehunmonkgroup** [comment]
I've looked at this further, and concluded implementing this unnecessarily over-complicates the code base.

The ```taskrc``` override in ```config.ini``` is meant to provide a simple mechanism to point to another config file. It was never my intention to re-implement all the TaskWarrior config options in VIT.

The current mechanism allows enough flexibility for setting a custom data location IMO (placing it in the configured taskrc file, or using the `TASKDATA` environment variable, which TaskWarrior will use under the hood.
