### ISSUE TITLE
Due date is not shown in the overdue report

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#259]
Vit 2.0.0, task v2.5.1

The list of overdue tasks is correct, but the actual due date is not displayed

**Comment by thehunmonkgroup** [comment]
Works fine for me.

VIT does not generate custom layouts for reports, it reads the layout directly from TaskWarrior. You can examine the layout that TaskWarrior is using for a report like so (this one is my current overdue report, which includes the date):

```
task _show | grep report.overdue
report.overdue.columns=id,start.age,entry.age,depends,priority,project,tags,recur.indicator,scheduled.countdown,due,until,description,urgency
report.overdue.description=Overdue tasks
report.overdue.filter=(status:pending or status:waiting) and +OVERDUE
report.overdue.labels=ID,Active,Age,Deps,P,Project,Tag,R,S,Due,Until,Description,Urg
report.overdue.sort=urgency-,due+
```

**Comment by fdela** [comment]
I got exactly the same (default) overdue report configuration.
Weird thing is that `task overdue` _does_ show the due date, while `vit` doesn't.

I've made no change to default .vit/config.ini file either.
The due date is well present in `task export` output, e.g. 
```
[
{"id":23,"description":"foobar","due":"20200724T220000Z","entry":"20200722T230242Z","modified":"20200722T231128Z","status":"pending","uuid":"6bfee969-786c-4a3a-bfe7-2adbb979accd","urgency":11.5264}
]
```
For that task, the overdue report gives:
| ID | Age | Due | Description | Urg |
| ---|---|---|---|---|
|23|3d|2020-07-25|foobar|11.5|

in task (date difference is due to local time), and 
| ID | Age |Description | Urg |
| ---|---|---|---|
|23|3d|foobar|11.5|

in vit.

**Comment by thehunmonkgroup** [comment]
Can you create a test case for me?

https://github.com/scottkosty/vit/blob/2.x/TEST-CASE.md

**Comment by fdela** [comment]
> Can you create a test case for me?
> 
> https://github.com/scottkosty/vit/blob/2.x/TEST-CASE.md

See attached file for test case (had to rename it in .txt do github would accept upload)
Local time = CEST (UTC+2)

For that task, the _overdue_ report gives:
| ID | Age | Due | Description | Urg |
| ---|---|---|---|---|
|1|11min|2020-07-26|a|9.7|

in `task`  and 
| ID | Age |Description | Urg |
| ---|---|---|---|
|1|11min|a|9.70|

in `vit`.

`task 1 export` gives:
```
[
{"id":1,"description":"a","due":"20200725T220000Z","entry":"20200727T211416Z","modified":"20200727T211416Z","status":"pending","uuid":"43700448-6395-4e63-b5c9-3e0c64bdaa7a","urgency":9.70287}
]
```

`task 1 info` gives:

|Name |         Value|
|---|---|
|ID        |    1|
|Description   |a|
|Status        |Pending|
|Entered      | 2020-07-27 23:14:16 (11min)|
|Due           |2020-07-26 00:00:00|
|Last modified |2020-07-27 23:14:16 (11min)|
|Virtual tags  |MONTH OVERDUE PENDING READY UNBLOCKED WEEK YEAR YESTERDAY LATEST|
|UUID          |43700448-6395-4e63-b5c9-3e0c64bdaa7a|
|Urgency      | 9.704|


[no-due-date-in-overdue-report.sh.txt](https://github.com/vit-project/vit/files/4984510/no-due-date-in-overdue-report.sh.txt)

**Comment by thehunmonkgroup** [comment]
The test case works perfectly in my installation:

```sh
task overdue
TASKRC override: /tmp/tmp.z4CF0qGyva.vit/taskrc

ID Age Due        Description Urg 
 1 32s 2020-07-26 a           9.54

1 task
```
![vit-overdue-test](https://user-images.githubusercontent.com/43772/88596754-abe72200-d01a-11ea-8385-977d3f9c459b.png)

```sh
task 1 export
TASKRC override: /tmp/tmp.z4CF0qGyva.vit/taskrc
[
{"id":1,"description":"a","due":"20200726T070000Z","entry":"20200727T220336Z","modified":"20200727T220336Z","status":"pending","uuid":"ac693124-552d-4112-8363-aed8a6d97021","urgency":9.54479}
]
```

So at this point it seems more likely an issue with your setup. It's possible there's a parsing error with VIT in the TaskWarrior config, but that is unlikely, and would be difficult to track down without more clues.

**Comment by fdela** [comment]
> So at this point it seems more likely an issue with your setup. It's possible there's a parsing error with VIT in the TaskWarrior config, but that is unlikely, and would be difficult to track down without more clues.

Content of my $TASKRC file: `data.location=/tmp/tmp.tPfGdBFCjZ.vit/task`
`$VIT_DIR/config.ini` is empty

I tried with 2 different machines, with a similar setup, for same results: Window 10 v1903, WSL1, Ubuntu (20.04), taskwarrior 2.5.1, vit 2.0.0 (default packages).
I also installed another distribution with WSL, same issue.

Is there a specific "debug mode" in VIT I could use to try and see where if fails?

**Comment by thehunmonkgroup** [comment]
I cleared out my ```config.ini``` to completely replicate your test, and there's still no issue.

https://github.com/vit-project/vit/blob/2.x/DEVELOPMENT.md#debugging for dumping vars to a file.

```set_column_metadata``` in ```task_list.py``` is probably a decent place to start.

**Comment by fdela** [comment]
I checked with latest vit from 2.x branch (be85553) and it worked correctly (as opposed to the v2.0.0 I used to report this issue).
It seems 7200949 has fixed that issue.

**Comment by thehunmonkgroup** [comment]
For future reference, especially at the pace of issue reporting you're doing, it would be best if you always verified the issue against the end of the ```2.x``` branch before reporting.
