### ISSUE TITLE
Error when task list is empty

### ISSUE THREAD

**Issue by ghost** [vit-project/vit#262]
**Describe the bug**
When the list is empty, this error happend and the app exit: Fatal error: ```default.command ("next") must print an "ID" column```

**To Reproduce**
Delete all tasks.

**Expected behavior**
Just say the list is empty.

**Comment by scottkosty** [comment]
I believe this is fixed on as of vit 2.0.0.

**Comment by ghost** [comment]
Ah, I see. Could you please package vit 2.0 for arch-linux. The one in repo is 1.3.

**Comment by scottkosty** [comment]
Sorry, I don't know anything about arch (I would like to learn someday). And generally, the downstream packagers for a distro are often different from the maintainers of the upstream project. You might want to check out [this](https://www.archlinux.org/packages/community/any/vit/) page for contacts for Arch. If you do contact them, let them know that moving to 2.0 is a big change and has completely different dependencies from 1.3.
