### ISSUE TITLE
Project name completion only works for projects with pending tasks

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#265]
**Describe the bug**
When trying to autocomplete _project_ (using e.g. (a)dd,  (m)odify or (p)roject command), only projects which have at least one pending task are available (tested in _next_ and _all_ reports).

**To Reproduce**
Try to change a task project using _m_ or _p_ autocomplete, and hit tab key repeatedly to try and find a project which has currently no pending task.
In provided test case, p2 has a pending task, while p1 and p2.sub have none.

**Expected behavior**
Autocomplete should show all available project names, whether they currently have any pending task or not, upon hitting tab key repeatedly.
In provided test case, p1, p2 and p2.sub should be available (and possibly empty string).

**Test case**
[project-name-completion.sh.txt](https://github.com/vit-project/vit/files/5065724/project-name-completion.sh.txt)

**Notes**
- `task rc.list.all.projects=yes _projects` can be used to retrieve the full list of used projects in a TaskWarrior backward-compatible way (tested with 2.4.4 and 2.5.1).
- This would also be consistent with tag completion behaviour.

**Comment by thehunmonkgroup** [comment]
Does this work differently in TaskWarrior? I believe I get the list of available projects from there.

**Comment by fdela** [comment]
`task _projects` returns the list of projects with pendings tasks only (although manpage says it returns _all_ project names used).

You can use `task _unique project` to actually return the whole list, but it's only available in TaskWarrior 2.5.0+.
Alternative is `task rc.list.all.projects=yes _projects` which also works for 2.4, hence should be the preferred way for compatibility IMO.

**Comment by thehunmonkgroup** [comment]
Should be fixed, please verify.

**Comment by fdela** [comment]
> Should be fixed, please verify.

Works as expected
