### ISSUE TITLE
print.empty.columns truthness values are not properly handled

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#266]
**Describe the bug**
In taskwarrior configuration file, boolean truthness values can be represented by the following values, _case insensitive_ (from `taskrc` manpage):
> Note  that  Taskwarrior is flexible about the values used to represent Boolean items. You can use "on", "yes",
       "y", "1" and "true".  Anything else means "off".

 `vit` only accepts _yes_ (lowercase) to represent truth in `print.empty.columns` config variable.

**To Reproduce**
1. Configure `print.empty.columns` with any of the above mentionned truthness values, case insensitive, except _yes_ (attached test case uses _True_)
1. Display `next` report
1. Compare with `task next` output

=> Columns with no data are not displayed

**Expected behavior**
Columns with no data are displayed.

**Affected code**
https://github.com/vit-project/vit/blob/1e1d010d0c807d131746bb2443c7f6b1e40cb847/vit/config_parser.py#L220-L221

Something like
```python
self.print_empty_columns = self.subtree('print.empty.columns').lower() in ['y', 'yes', 'on', 'true', '1']
```
would fix this specific issue.

**Test case**
[print-empty-columns.sh.txt](https://github.com/vit-project/vit/files/5091966/print-empty-columns.sh.txt)

**Comment by thehunmonkgroup** [comment]
Should be fixed, please verify.

**Comment by fdela** [comment]
> Should be fixed, please verify.

Works as expected
