### ISSUE TITLE
Can't set priority when uda.priority.values is customized

### ISSUE THREAD

**Issue by fdela** [vit-project/vit#269]
**Describe the bug**
**P** (modify task priority) command doesn't take customized priority values into account: it only allows modifying priority by using _h_, _m_, _l_ or _n_.

**To Reproduce**
Run test case to use `uda.priority.values=A,B,C`

1. Try to use **P** to change priority to _C_ on task 1 => impossible (doesn't do anything)
1. Try to use **P** to change priority to _h_ on task 1 => crash

**Expected behavior**
1. You should be able to set priority to _C_
1. Should be a no-op (ideally display an/Taskwarrior error message)

`Priority (h,l,m,n)` should not be shown but `Priority (A,B,C)` should be displayed instead (`n` [none] to reset priority field could probably be left out).
Alternatively, a mere `Priority` could be shown instead, provided autocompletion is available, as with modify task **p**roject command.

**Test case**
[priority-alternate-values.sh.txt](https://github.com/vit-project/vit/files/5215074/priority-alternate-values.sh.txt)

**Comment by thehunmonkgroup** [comment]
Couple thoughts off the top:

1. The priority UDA is a complete pain in the ass
2. You are uncommonly good at finding esoteric bugs in my code ;)

Should be fixed in master, please verify, with these caveats:

 * Because of the way key presses are detected, and for backwards compat, `n` is still the key used to remove priority. This means that you can't use `n` or `N` as a priority value, which is unfortunate and ugly, but will have to do for now.
 * Also for backwards compat and ease of use, the choices are lowercased. This means you can't use both `a` and `A` as priority values if you want this functionality to work properly. This seems reasonable.

**Comment by fdela** [comment]
After testing fce27ac, I can't reset priority using `n`.
`Priority (a/b/c)` is shown instead of `Priority (a/b/c/n)`

**Comment by thehunmonkgroup** [comment]
I believe this is a configuration error on your part:

```dosini
uda.priority.values=H,M,L,
```

**Comment by ifohancroft** [comment]
To me, it sounds like the problem I was having. Not exactly, but in the sense that the same fix would fix it: https://github.com/vit-project/vit/commit/79bc2e92fa46970e7097b5ced005bb3f8d1d86ec

**Comment by fdela** [comment]
> I believe this is a configuration error on your part:
> 
> ```ini
> uda.priority.values=H,M,L,
> ```

Not sure where you got this. After executing my test script, I get:
```console
foo@bar:path$ cat $TASKRC
data.location=/tmp/tmp.gK7fL1qmxv.vit/task
uda.priority.values=A,B,C

foo@bar:path$ task show uda.priority.values
TASKRC override: /tmp/tmp.gK7fL1qmxv.vit/taskrc

Config Variable     Value
uda.priority.values A,B,C
  Default value     H,M,L,

Some of your .taskrc variables differ from the default values.
  These are highlighted in color above.
```

As I said earlier, I can now change priority to one of `a`, `b` or `c`, but cannot use `n` to reset it.

After some testing, it looks like your code considers `uda.priority.values` to always contain the empty value, which is not happening in my test case.
When this happens, the change priority command should still allow to reset priority (i.e. to remove the `priority` attribute from selected task).

I haven't seen anywhere that empty values should be mandatory in uda values list (at least not in [TW UDA doc](https://taskwarrior.org/docs/udas.html)).

**Comment by thehunmonkgroup** [comment]
> After some testing, it looks like your code considers uda.priority.values to always contain the empty value, which is not happening in my test case.

This is incorrect. The existence of an empty value is determined by the `uda.priority.values` setting.

This setting has an empty value: 
```dosini
uda.priority.values=A,B,C,
```

This setting has no empty value:
```dosini
uda.priority.values=A,B,C
```

It's up to the user to decide if they want to be able to set the priority to empty or not. The code must base its behavior on the setting, as it cannot know the user's intention any other way. Imagine, for example, that a user doesn't ever want an option to set the priority empty. They can do this by not including an empty option in the config, and forcing a default priority on task creation through a hook.
