### ISSUE TITLE
Allow disabling flash

### ISSUE THREAD

**Issue by bruno-** [vit-project/vit#270]
**Is your feature request related to a problem? Please describe.**

When I use `vit` and perform an action like "start a task" and "stop a task" the task I'm working on flashes.

I believe the internal function used for this is `flash_focus`.

**Describe the solution you'd like**

Ideally, I would like to disable flashing completely via config option or similar.

**Additional context**

I'd like `vit` to be as fast as possible so I don't like waiting for flashes.

**Comment by thehunmonkgroup** [comment]
Probably the most robust way to handle this is to provide two configuration options in the `[vit]` section of `config.ini`:

 * `flash_focus_repeat_times`
 * `flash_focus_pause_seconds`

There would be some necessary refactoring for those config options to be properly passed down, with the current defaults kept.

I would consider a PR for this feature, but probably will not implement it myself.

**Comment by rcurtin** [comment]
For anyone looking for a super quick solution that doesn't mind running vit from source, here's a patch that disables blinking:

```
diff --git a/vit/task_list.py b/vit/task_list.py
index 8b7e28d..485fd8a 100644
--- a/vit/task_list.py
+++ b/vit/task_list.py
@@ -151,10 +151,10 @@ class TaskTable(object):
             position = self.listbox.focus_position
         self.list_walker[position].row.set_attr_map({None: attr})
 
-    def flash_focus(self, repeat_times=2, pause_seconds=0.1):
+    def flash_focus(self, repeat_times=0, pause_seconds=0.1):
         if self.listbox.focus:
             position = self.listbox.focus_position if self.listbox.focus_position is not None else self.listbox.previous_focus_position if self.listbox.previous_focus_position is not None else None
-            if position is not None:
+            if position is not None and repeat_times > 0:
                 self.update_focus_attr('flash on', position)
                 self.draw_screen()
                 for i in repeat(None, repeat_times):
```

I think I have some idea of what would need to be done for a PR here; I'll see if I can manage to find the time to clean it up and do it right and submit that in the next days.
