### ISSUE TITLE
Vit stuck on "loading..."

### ISSUE THREAD

**Issue by redquixote** [vit-project/vit#276]
Hello there,

My vit stopped working and just shows "Loading..."

- vit --help   =>  works
- vit {string}    => works but shows only tasks with {string} in the title.

There are no errors anywhere.

What I tried and failed:
- reinstalling
- downloading the code from here and installing it  on a clean virtualenv 
- check if taskwarrior was broken (Removed plugins etc)
- changing the default report on config.ini

If I ctrl-c vit I get this:

```
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.0.0', 'console_scripts', 'vit')())
  File "/usr/lib/python3.9/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.9/site-packages/vit/application.py", line 75, in __init__
    self.loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 814, in _loop
    ready, w, err = select.select(fds, [], fds)
KeyboardInterrupt
```
I'd appreciate any pointers to fix the issue.

Vit is such an important part of my work! 

Thanks in advance,

RQ

PS: I did update to python3.9 last week but the issue only appeared last Friday and there are no issues or errors regarding python.

**Comment by scottkosty** [comment]
It sounds like there is one task in particular that is causing issues. To figure out what that task is:

1. First, backup everything.
2. Then, start "bisecting" your pending.data file to figure out which line causes the problem.
3. Then anonymize that line and post it here.

Let me know if (2) is confusing and I can give more details.

**Comment by redquixote** [comment]
Thank you @scottkosty !
I didn't know a rogue task could brake vit!

I found and deleted the evil task on pending.data and I have my beloved vit back.

the task in question:

`
[annotation_1607673381:"autonote" description:"contact owner regarding blue the parrot" entry:"1607673181" modified:"1607680812"  project:"" status:"pending" tags:"tg,next" uuid:"a81b3ec1-0d89-4888-86b3-cf741ac0f67c"]
`

It can't be seen above but project has these characters:  "^[^[" 
I imagine that was the problem. Now, I have no idea how those got there.

Thanks again,

RQ
