### ISSUE TITLE
vit 2.0.0_2 with TW 2.5.3: KeyError: 'columns' when launching

### ISSUE THREAD

**Issue by monkeyxite** [vit-project/vit#280]
**Describe the bug**

vit 2.0.0_2 with TW 2.5.3 popped up with  KeyError: 'columns' when launching:

**To Reproduce**

After upgrade into TW 2.5.3. It works fine with 2.5.1.

**Expected behavior**

A temp fix by using [bf4cb06](https://github.com/vit-roject/vit/commit/bf4cb069228e12b26e436b120fb9938a2b6a1531).

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.

**Comment by thehunmonkgroup** [comment]
VIT 2.0 is not compatible with Taskwarrior > 2.5.1.

You can use v2.1.0b2 or the development branch for compatibility with Taskwarrior 2.5.2 and beyond.
