### ISSUE TITLE
Adding and editing of field value, relative to another task

### ISSUE THREAD

**Issue by ifohancroft** [vit-project/vit#281]
**Is your feature request related to a problem? Please describe.**

99% of my use of TaskWarrior relies on the use of the Priority UDA field/column. For example, in my 'Learn' project, I have about 10 different tasks that are sorted based on Priority in descending order and if I want to add a task somewhere in the middle, I have to either modify the priority of all tasks above it or if I don't mind using negative numbers (as usually I like to start my Priority from 0) edit all those below it.

**Describe the solution you'd like**

In the case of Adding a task: I would like the ability to select an integer column (in my case Priority) and be able to either add a specific integer for the value or choose Higher Than/Less Than/Equal to and an existing task or Between and two existing tasks, where and for Vit to adjust the values of the other tasks accordingly.

In the case of Editing an existing task: I would like to be able to move the task up and down the list, adjusting the value of the configured field (Again, Priority in my case) with that. So lets say I select task with Priority of 2 and above it, there is a task with Priority of 3, I hit Shift + K or something like that and after hitting it once, the task's Priority becomes the same as the task above it, essentially, now they both have Priority of 3. If, before saving, I hit Shift+K twice instead, the task's priority, needs to become higher than the priority of the task above it, essentially the task that used to have Priority of 2 will now have a Priority of 3 and the one that had 3 will now have 2. Or perhaps some other way to differentiate between editing the value as absolute or relative to another task's value.

To clarify on the Editing scenario:
I am not asking for this to be incorporated into the view itself as well. Instead I am asking for the ability to assign a key-combo or pre-defined key-combo to increase/decrease the value of a field/column, with the view updating in real time depending on how you have set the sorting. In my case, I am sorting on 'project,depends,priority-' so when I use the use the key combo to change the priorities, I would like the view to reflect that in real time.

P.S. I believe this should respect task projects. If a task is added to a project, when changing or even adding a priority to it (whether to a pre-existing task or while adding a new one) it should change the priority only of the other tasks that are also in the same project. If the task is not in a project, the priority value should only affect other tasks not in a project as well.

**Comment by thehunmonkgroup** [comment]
This is *way* out of scope for VIT. I understand the desire to have some kind of method to do rank ordering in Taskwarrior, I've wanted that myself many times.

Taskwarrior, however, is built around the calculated urgency paradigm. If you want some automated way of rank ordering, you'll have to build it yourself, or find it from the community.

Whatever script you come up with, you can pretty easily hook that to a key combination in VIT, and VIT makes the task uuid of the currently selected task available in the keybinding syntax, so you can even pass that into your custom ordering script. See https://github.com/vit-project/vit/blob/2.x/vit/config/config.sample.ini

**Comment by ifohancroft** [comment]
> Whatever script you come up with, you can pretty easily hook that to a key combination in VIT, and VIT makes the task uuid of the currently selected task available in the keybinding syntax, so you can even pass that into your custom ordering script. See https://github.com/vit-project/vit/blob/2.x/vit/config/config.sample.ini

Thank you! I didn't know that was possible on the VIT side of things. This definitely makes things easier to make it as a custom solution.

Are the following possible:
1. Updating the view in real time if you have ordered by a certain column and the value of the tasks for that column/field changes?
2. Either telling VIT which task to highlight/select or keeping the highlight on the previously selected/highlighted task after the view updates?

**Comment by thehunmonkgroup** [comment]
> Updating the view in real time if you have ordered by a certain column and the value of the tasks for that column/field changes?

I'm not exactly sure what you mean by 'real time', but if you run a shell command, VIT will reload the report after the shell command exits and you hit enter to confirm.

> Either telling VIT which task to highlight/select or keeping the highlight on the previously selected/highlighted task after the view updates?

VIT selects the same task on report reload if it's still available in the report.

**Comment by ifohancroft** [comment]
Thank you!
