### ISSUE TITLE
KeyError: 'sort' when using custom reports without a sort property defined

### ISSUE THREAD

**Issue by bremme** [vit-project/vit#282]
**Describe the bug**
I read some good things about `vit` so just wanted to give it a go. So went along and installed `vit` using `pip`. After the install completed I ran `vit`. Answered `y` to create a default config. This gave me a `KeyError` and the following trace:
```shell
/home/bremme/.vit/config.ini doesn't exist, create? (y/n): y

/home/bremme/.vit/config.ini created. This is the default user configuration file. 

It is heavily commented with explanations and lists the default values for all available user configuration variables. Check it out!

Press enter to continue...
Traceback (most recent call last):
  File "/home/bremme/.pyenv/versions/3.9.1/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/config_parser.py", line 336, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/config_parser.py", line 340, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/home/bremme/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vit/config_parser.py", line 347, in has_primary_project_ascending_sort
    primary_sort = report['sort'][0]
KeyError: 'sort'
```
I checked and the configuration file is created. I looked a bit further into the issue (both `taskwarrior` and `vit` are new to me). And found the root cause of the problem. I have defined a couple custom `report`s in my `.taskrc` file (I followed one of the guides linked from the task warrior website: https://cs-syd.eu/posts/2015-06-21-gtd-with-taskwarrior-part-2-collection). It seems that `vit` requires the `report.<custom_name>.sort` property to be defined and does not have a default fallback mechanism like task warrior itself has.

After I found this, I tested to run `vit` with and without the `sort` property defined. When all custom reports have a `sort` property defined `vit` seems to work fine.

This is probably a small fix and it does confuse new users like myself.

**To Reproduce**
Run `vit` while you have added custom reports to your `.taskrc` without the `sort` property defined. My system:

* Ubuntu 20.04 (couple weeks old)
* taskwarrior 2.5.1 (apt install taskwarrior)
* Python 3.9.1 (installed using PyEnv)
* vit 2.0.0

**Expected behavior**
I expect the application to launch.

**Comment by thehunmonkgroup** [comment]
Already fixed in https://github.com/vit-project/vit/pull/238

VIT will have a new stable release in the near-ish future, in the meantime, you can use the latest beta which already has this fix: https://pypi.org/project/vit/2.1.0b1/

**Comment by bremme** [comment]
Thanks!
