### ISSUE TITLE
Please add a hint to the opening screen!

### ISSUE THREAD

**Issue by kwoot** [vit-project/vit#283]
**Is your feature request related to a problem? Please describe.**

As a new user I have no clue what the key bindings are.

**Describe the solution you'd like**

A hint on the main screen to "type :help to see the manual" or something to that effect.
Adding this to the man page would probably also work.

**Additional context**

I had to find the ":help" hint by browsing issues.

**Comment by thehunmonkgroup** [comment]
I'm in support of making it easy for users to find help. I do however want to avoid duplication or polluting the interface unnecessarily.

VIT is a command-line program, and command-line programs have a common convention that ```-h``` or ```--help``` outputs basic help information, which VIT also implements.

```vit --help``` already includes a reference to executing ```:help``` when VIT is running:

```
While VIT is running, type :help followed by enter to review basic command/navigation actions.
```

This feels pretty sufficient to me as far as guidance in the codebase itself.

How about we add a ```Usage``` section to to the main [README](/https://github.com/vit-project/vit/blob/2.x/README.md)? In that section we can reference both ```vit --help``` and ```:help``` within VIT.

**Comment by kwoot** [comment]
Ah, yes, you are completely right. Somehow I overlooked that remark on the --help output. 
Maybe also add a small line to the manual page?
You know, for people who can't read the --help output :-).

**Comment by thehunmonkgroup** [comment]
Fixed in https://github.com/vit-project/vit/commit/cfe5975bd054fe8ffe79527a1af6356528b60c63

Viewable at https://github.com/vit-project/vit#quick-start
