### ISSUE TITLE
Recurrence template deleted with cmd D

### ISSUE THREAD

**Issue by jaker-dotcom** [vit-project/vit#288]
It occured to me that capital D command deletes all pending instances of a recurring task and the recurrence template. 

It should behave as the "done" command lowercase d that seems to only mark one instance of the task as done.

Workaround: Hit t for prepending the shell command with "!rw task" and then delete the instance of the recurring task via command. The shell is interactive and this works.

PS: New user, perhaps doing something stupidly wrong. But since vit is otherwise rather intuitive I think this must be an error.

**Comment by thehunmonkgroup** [comment]
I'm using the `delete` method from `tasklib`, as seen here: https://github.com/robgolding/tasklib/blob/develop/tasklib/task.py

So if there's an issue with the way it handles deletion of recurring tasks, you may want to file the bug there.

I'd recommend first, though, seeing if you can replicate the behavior in TaskWarrior itself -- it doesn't always behave the way I expect :)

**Comment by jaker-dotcom** [comment]
Have been using taskwarrior for quite some time so I'm pretty positive it's not coming from there. 
For now I'll just avoid doing so in vit but when I have time I'll look into tasklib. 

Have you been able to reproduce it though?

Thank you for maintaining vit!

**Comment by thehunmonkgroup** [comment]
I don't really use recurrence. On a quick test, it looks to be working OK for me:

![recur-delete](https://user-images.githubusercontent.com/43772/112663589-a565b000-8e1e-11eb-8901-97bd2063c6ef.png)

What I think I see there is that I've deleted the task, but the template is not deleted.
