### ISSUE TITLE
change thresholds for due column colors

### ISSUE THREAD

**Issue by bgravato** [vit-project/vit#293]
I'm using vit 2.1.0

On the due column, if due time is less than 7d it becomes red. I'd like to change this threshold to less than 3d instead of 7d. Is this possible?

In addition it would be great if I could add an extra level and make it yellow or orange if due is between 3d and 5d.

I've searched the docs, but couldn't find anything about it.

Thanks

**Comment by thehunmonkgroup** [comment]
You'll need to check the TaskWarrior docs, and edit `.taskrc` accordingly to adjust *when* an item is considered overdue, and the associated color.

I don't know about different levels of warning. Due and overdue are the two I know of.

**Comment by bgravato** [comment]
Thanks for pointing in the right direction.

To change the threshold I just had to add `due=3` to .taskrc

For having dual threshold I guess it will only be possible if that feature is added to taskwarrior itself.
