### ISSUE TITLE
Adding all info in a row?

### ISSUE THREAD

**Issue by xarthurx** [vit-project/vit#294]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently, I need to press `a` for adding a task, `p` for changing priority, `P` for changing project, `T` for changing tags....
Is there a way to add everything in a row, by pressing `a` and asking for the info one by one?
Empty input will make the entry empty by default.

**Additional context**

**Comment by thehunmonkgroup** [comment]
Standard TaskWarrior syntax works fine for the add command.

For example, `task add priority:H Pay bills` in TaskWarrior would translate in VIT to hitting the `a` key, then typing `priority:H Pay bills`

The TaskWarrior documentation has plenty of examples: https://taskwarrior.org/docs/examples.html

**Comment by xarthurx** [comment]
So... `vit` is not supposed to be built as a complete taskwarrior UI?
(I also find that there's no way to add dependency to the project inside VIT. )
