### ISSUE TITLE
Appening ".monthly" when adding "history" to task description

### ISSUE THREAD

**Issue by arawnx** [vit-project/vit#295]
**Describe the bug**
When I add the word "history" to a task description (through any means other than the vim editing mode triggered by pressing **e**), the task description is modified, but instead of "history," "history.monthly" is written.

**To Reproduce**
1. Add a new task
2. Press **m** to modify its description
3. Change its description to "history"
4. Observe its new description is "history.monthly"

**Expected behavior**
".monthly" should not be appended.

**Comment by thehunmonkgroup** [comment]
This is a TaskWarrior bug, see below:

```
# task add this is a history lesson
Created task 1.
# task list

ID Age  Description                          Urg 
 1 3s   this is a history.monthly lesson        0

1 task
```

Recommend you file the bug in the TaskWarrior issue queue: https://github.com/GothenburgBitFactory/taskwarrior/issues
