### ISSUE TITLE
Join taskwarrior discord server!

### ISSUE THREAD

**Issue by linuxcaffe** [vit-project/vit#297]
**Is your feature request related to a problem? Please describe.**
There's a taskwarrior discord server set up, and the vit developers and users aren't yet there, to join in the discussion!

**Describe the solution you'd like**
Vit devs and users follow invite link;  https://discord.gg/q8xEDz6SCK

**Additional context**
There's a #vit channel, for discussion about vit-specific stuff!
It's even possible, even optimal, to have activity on this repo reflected in that #vit channel!

**Comment by thehunmonkgroup** [comment]
OK, I installed discord and accepted the invitation. Not sure I'll ever see any messages, though -- I already have too many messaging apps, and won't have Discord open hardly ever. If there's some way to get an email notification when something is posted in #vit, that would be helpful.
