### ISSUE TITLE
Vit ignores new taskwarrior configuration 'report.X.context'

### ISSUE THREAD

**Issue by RonMcKay** [vit-project/vit#307]
**Describe the bug**
In taskwarrior 2.6.0 there is a new configuration option for reports to ignore the currently set context `report.<name>.context=0`.
Vit seems to ignore this new setting.

**To Reproduce**
In a `.taskrc` put the following:
```
report.next.context=0
context.work.read=project:Work
context.work.write=project:Work
```

Then execute the following:
```
task context none
task add project:Work First Task
task add SecondTask
task context work
```
Then show the 'next' report in vit

**Expected behavior**
The report should show both tasks 'First Task' and 'Second Task'.
The 'next' report in vit however does only show the 'First Task'

**Test case**
I have attached the modified `generate-dummy-install.sh` which reproduces the issue (I had to change the filetype to `.txt` to be able to attach it to this issue).
[generate-dummy-install.txt](https://github.com/vit-project/vit/files/7318354/generate-dummy-install.txt)

In my setup I use the following vit and taskwarrior versions:
vit: Commit 0df4841
taskwarrior: 2.6.0

**Comment by thehunmonkgroup** [comment]
May not have time to look at this for awhile, I would welcome a pull request to address the issue.

**Comment by RonMcKay** [comment]
I created a pull request but as I do not have a complete overview of the code base I might have missed something.
