### ISSUE TITLE
Can this project participate in Hacktoberfest?

### ISSUE THREAD

**Issue by arozans** [vit-project/vit#309]
Hello, i admire vit as much as I admire taskwarrior, both are eminently useful in my workflow, thanks for that project.
I'm thinking about contributing in some way and ongoing Hacktoberfest seems to be great excuse to do so. What do you think about marking this repo with "hacktoberfest" topic? More info here: https://github.blog/2021-10-07-githubs-guide-hacktoberfest-2021/#participating-as-a-maintainer

**Comment by thehunmonkgroup** [comment]
I added the tag
