### ISSUE TITLE
ACTION_REFRESH keybind triggers while entering text

### ISSUE THREAD

**Issue by thomas2p** [vit-project/vit#313]
**Describe the bug**
Any key bound to ACTION_REFRESH in config.ini will trigger while typing (eg. adding a new task).
**To Reproduce**
Add the following line to your `config.ini` below `[keybinding]`:
`r = {ACTION_REFRESH}
`Open vit and press a to add a new task. Type some sentence that includes the letter r. The prompt will be gone and no task will be added.

**Expected behavior**
Nothing - you should be able to enter text without triggering the key binding.

**Comment by thehunmonkgroup** [comment]
Can you please test a few other keybindings? I suspect this might only be an issue with `ACTION_REFRESH`, as I recall it uses some kind of special callback which may not play well with input fields.

**Comment by thomas2p** [comment]
> Can you please test a few other keybindings? I suspect this might only be an issue with `ACTION_REFRESH`, as I recall it uses some kind of special callback which may not play well with input fields.

Your suspicion is correct, other actions are not affected. I've updated the issue.
