### ISSUE TITLE
Broken links on PyPi

### ISSUE THREAD

**Issue by vEnhance** [vit-project/vit#317]
**Describe the bug**
All the `*.md` links on https://pypi.org/project/vit/ are broken.

**To Reproduce**
Click any link to an md file.

**Expected behavior**
USers should be redirected to this wiki (or elsewhere), but are given a 404 error instead.

**Comment by thehunmonkgroup** [comment]
This is a function of the difference between how Github handles the markdown for those links and PyPi handles the markdown.

On Github, the markdown is correctly translated into a link for the correct file on the correct branch.

PyPi has no such special treatment, and instead translates the markdown relative pypi.org.

I'm not really sure I want to fix this, as the fix would include hardcoding links to the current main branch of VIT, which would lose the work Github does to keep them current.

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files
