### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eddsalkield** [vit-project/vit#318]
Firstly, thanks so much for your work on vit - I've been giving it a try, and it seems really useful!  I'm looking to create a vit package for Alpine Linux, but the latest release seems to not contain the [XDG base directory specification patch](https://github.com/vit-project/vit/pull/198), which is quite important to my workflow.

Would you consider cutting a new release at some point soon?

**Comment by thehunmonkgroup** [comment]
https://github.com/vit-project/vit/releases/tag/v2.2.0b1 contains that merged PR.
