### ISSUE TITLE
UI omits end date column

### ISSUE THREAD

**Issue by bradyt** [vit-project/vit#319]
Taskwarrior 2.6.1, taskwarrior-tui 0.18.3.

I created a report to view logged items, at .taskrc as follows:

```
% cat .taskrc
report.Log.columns     = end,description
report.Log.description = Log
report.Log.labels      = Done,Description
report.Log.sort        = entry+
report.Log.filter      = status:completed
```

When I run `taskwarrior-tui -r Log`, I expect to see two columns with the logged date and the description, but the end date column is completely omitted, and only the column of descriptions is seen.

I tried `M-x rgrep`'ing the source for `description`, this all seems to happen in `./src/task_report.rs`, in `get_string_attribute`. Looking at that, I wondered if `report.Log.columns = entry,description` would also not work. It looks like putting `entry`, rather than `entry.age`, would also be an omitted column. That seemed to confirm I was in the right place.

Looks like a bit of work, both to decide whether to allow more column types, then which ones, if more than one more, and then to go about implementing one more or even more of these. I hope this isn't just me, that you already wanted to add more columns, but just had found a convenient place to postpone implementing more.

**Comment by thehunmonkgroup** [comment]
You're reporting this on the VIT project, perhaps you meant to report to https://github.com/kdheepak/taskwarrior-tui ?

**Comment by bradyt** [comment]
> You're reporting this on the VIT project, perhaps you meant to report to https://github.com/kdheepak/taskwarrior-tui ?

Oops! That is correct, meant to file at other project. Pardon me, thank you!
