### ISSUE TITLE
Customize task executable

### ISSUE THREAD

**Issue by CaptainQuirk** [vit-project/vit#324]
**Is your feature request related to a problem? Please describe.**

I'm trying to install [`go-task`](https://github.com/go-task/task) alongside taskwarrior. Both programs share the same binary name. `go-task` already has sufficient momentum so that changing the binary name may cause problems.
I could alias taskwarrior locally, but vit would still use `task`.

**Describe the solution you'd like**
Would it be possible to configure the path to the task executable in the `.ini` file ?

**Comment by thehunmonkgroup** [comment]
> Would it be possible to configure the path to the task executable in the .ini file ?

It's likely that this is possible, but the PR would have go be carefully reviewed to make sure there's no breakage, as the entire app assumes that `task` is the binary, and in the user's path.

Why not alias `go-task` instead?

**Comment by CaptainQuirk** [comment]
It's what I did yes !
