### ISSUE TITLE
SIGUSR1 breaks vit

### ISSUE THREAD

**Issue by davidoskky** [vit-project/vit#329]
**Describe the bug**
When I send SIGUSR1 to update the vit interface, if tasks have been added or removed from taskwarrior, vit crashes.
If no tasks have been added or removed, vit does not crash.

**To Reproduce**
start vit
use taskwarrior directly to add a task
kill -s 10 $PID_VIT

**Expected behavior**
The interface of vit updates and the new task is shown

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.

vit version: 2.2.0 (installed through pip)

**Comment by thehunmonkgroup** [comment]
Please try to reproduce with the development version of VIT: https://github.com/vit-project/vit/blob/2.x/DEVELOPMENT.md

If you can reproduce there, then include a backtrace of the crash.

**Comment by davidoskky** [comment]
I can reproduce on the latest commit.
Could you please provide guidance on how to get the backtrace?

There is no output on the terminal, except: "User defined signal 1" and it goes back to the terminal.

**Comment by thehunmonkgroup** [comment]
If VIT is actually crashing, it should dump a backtrace to your terminal.

**Comment by thehunmonkgroup** [comment]
I can also report that I cannot reproduce your issue, running latest VIT development.

**Comment by davidoskky** [comment]
There is no dump on the terminal.
Vit outputs User defined signal 1 and closes.
The exit code is 138.

**Comment by thehunmonkgroup** [comment]
Without a backtrace and not being able to reproduce, there's not a whole lot I can do.

It's more likely this is an issue with your setup, and not with VIT, or that you have some non-standard edge case that is getting hit.

The next step would be to use an entirely fresh TaskWarrior/VIT install, with a clean config and database, and see if you can reproduce in that environment. There's a script to help with that, that will set up a temporary install within the shell you run the script in: https://github.com/vit-project/vit/blob/2.x/scripts/generate-dummy-install.sh

**Comment by davidoskky** [comment]
I have tried with clean config and database and the same problem appears.
I am not running any particularly strange setup.
Fedora 36, bash, gnome terminal / konsole, linux kernel 5.18, taskwarrior 2.5.3

**Comment by thehunmonkgroup** [comment]
I'm not really sure there's any more assistance we can provide. The error you're reporting is not reproducible, it's not producing a backtrace, and you're not able to isolate a reason why it's happening.

I'll leave this issue open for now, in case you run across any additional data.

**Comment by davidoskky** [comment]
Alright, I understand.
If there is any action I could perform to debug this, let me know.

**Comment by awilkins** [comment]
Also seeing this,

Ubuntu 20.04
vit 2.2.0
task 2.6.2

I'm guessing this is because there has been no release of `vit` since this feature was added : the signal handler is introduced in revision 10c67 and version 2.2.0 is tagged three revisions before this. Versions installed from a package manager (including `pip`) won't have this feature.

I can confirm that it works fine from the source tree as of the HEAD of 2.x

```sh
python -m vit.command_line
```

**Comment by thehunmonkgroup** [comment]
https://pypi.org/project/vit/2.3.0/

**Comment by awilkins** [comment]
Many thanks!
