### ISSUE TITLE
display of project tags can be visually noisy because they are unsorted (patch attached)

### ISSUE THREAD

**Issue by sez** [vit-project/vit#334]
Hi, thanks for making vit!

**Is your feature request related to a problem? Please describe.**

Project tags are displayed in the order in which the user specified them, so two projects with the same tagset can be displayed differently, e.g.
- proj. a with tags foo,bar,next
- proj. b with tags next,foo,bar

have the same tags and yet it's not immediately obvious by staring at the tag list

**Describe the solution you'd like**

Displaly the tags in a consistent order. Please see the attatched patch (sending good old patch, as it's simple enough that a PR seemed overkill).

Thanks again!
[diff.txt](https://github.com/vit-project/vit/files/10540700/diff.txt)

**Comment by thehunmonkgroup** [comment]
> Display the tags in a consistent order.

Agreed, good idea.

> Please see the attached patch (sending good old patch, as it's simple enough that a PR seemed overkill).

Believe it or not, PRs are much easier to deal with than patch files, they:

 * Are easier to test
 * Are easier to merge
 * Give proper credit to the patch creator

So if you'll please make a PR out of that patch, I should be able to easily get this merged.
