### ISSUE TITLE
Bypass "Press Enter to continue..." when executing command from !wr

### ISSUE THREAD

**Issue by dnguyener** [vit-project/vit#338]
**Is your feature request related to a problem? Please describe.**
I want to not be prompted with "Press Enter to continue..." when executing a command utilizing !wr.

**Describe the solution you'd like**
Bypass the prompt and return directly to vit.

**Additional context**
Here is the line I've added to 
o = :!wr taskopen {TASK_UUID}<Enter>

**Comment by thehunmonkgroup** [comment]
https://github.com/vit-project/vit/blob/2.x/vit/config/config.sample.ini

```ini
wait = False
```
