### ISSUE TITLE
Clarify how to interact inside 'Denotate' window

### ISSUE THREAD

**Issue by Stefan-Radu** [vit-project/vit#340]
**Describe the bug**

Pressing <E> on an annotated task opens a window with a list of annotations and instructs you to
"Select the annotation, then select 'Denotate'". You can navigate with j/k, but cannot select, nor interact with the <denotate> / <cancel> buttons. Either not shortcuts are set or I cannot figure them out, as nothing is mentioned in the help. 

**To Reproduce**

1. open vit
2. navigate to a task with annotations
3. press <E>

**Expected behavior**

1. pressing <space> or other clearly mentioned shortcut should select / deselect annotations
2. navigating to the bottom with j should select <denotate>
3. after navigating to the bottom you should be able to also move to the right to <cancel>
4. pressing <enter> or other clearly mentioned shortcut should on the bottom two actions should perform the action
5. a concise help message shown on top would also be useful; something along the lines of "Select the annotation by pressing <Space>; select 'Denotate' or 'Cancel' then press enter." 

**Test case**

Task with annotations

**Comment by thehunmonkgroup** [comment]
Added this for clarity:

![2023-06-26_12-25](https://github.com/vit-project/vit/assets/43772/6c5fd3ed-5431-479f-b2e8-df5d25eaa431)
