### ISSUE TITLE
`vit` cli options / args

### ISSUE THREAD

**Issue by adriangalilea** [vit-project/vit#350]
**description**

I open vit from helix in a tmux popup window, this kind of window don't retain context so everytime I want to check my tasks for the project I'm working on I get everything which is the opposite of what I want since it distracts me with tasks that are not relevant now.

**solution**

allow for something like:
`vit -p foo` to start on a specific project
`vit-c bar` to start on a specific context

So when the tui opens it's already where I want it to be, plus it would allow scripting(which is why I want this.)

**consider**
I just learned about taskwarrior today, so there may be other potentially helpful options like tags and whatnot that may be good to add.

**Comment by thehunmonkgroup** [comment]
You can't get what you need via VIT's `config.ini`?

https://github.com/vit-project/vit/blob/2.x/CUSTOMIZE.md

https://github.com/vit-project/vit/blob/2.x/vit/config/config.sample.ini

**Comment by thehunmonkgroup** [comment]
VIT also accepts report/filter arguments (just like TaskWarrior), and it would be trivial to set up some shell aliases to run VIT with different args.

**Comment by adriangalilea** [comment]
> You can't get what you need via VIT's `config.ini`?

I don't know how could I do that, I've read it before your comment and checked again now, still can't figure out how can I set the config so it starts on a specific project.

> VIT also accepts report/filter arguments (just like TaskWarrior), and it would be trivial to set up some shell aliases to run VIT with different args.

I haven't seen this documented, but it worked! thanks!

EDIT: I'm still interested on the config.ini suggestion, it'd be better if I can set in the config.ini somehow the default project or filter

**Comment by thehunmonkgroup** [comment]
> I'm still interested on the config.ini suggestion, it'd be better if I can set in the config.ini somehow the default project or filter

The `[report]` section has settings for configuring a default report.

https://taskwarrior.org/docs/report/

**Comment by adriangalilea** [comment]
> > I'm still interested on the config.ini suggestion, it'd be better if I can set in the config.ini somehow the default project or filter
> 
> The `[report]` section has settings for configuring a default report.
> 
> https://taskwarrior.org/docs/report/

I see, I'm still trying to grasp many concepts of taskwarrior, so maybe it's just that I don't get it,

But how does a default report help me?

I want to associate a path with a project/context, so when I'm on that project and open vit or taskwarrior that it only shows me relevant tasks by default, but your suggestion seems more related to a general report system-wide, or are you  suggesting to have local `config.ini` per project and an enviroment variable that changes depending on the path I'm navigating that tells  to use the local `config.ini` and in that `config.ini` to somehow set a report that's relevant for the project?

**Comment by adriangalilea** [comment]
Just for reference to anyone perhaps searching for this in the future, I solved this with:
- direnv
- defining an `.env` with TASKWARRIOR_PROJECT env inside for the appropriate project
- script does `vit project:${TASKWARRIOR_PROJECT}"`
