### ISSUE TITLE
toggle next tag with shortcut

### ISSUE THREAD

**Issue by adriangalilea** [vit-project/vit#351]
It would be handy to be able to quickly toggle the +next tag with a key shortcut similar to<kbd>b</kbd> start/stop.

I managed to add this to the `config.ini`

```
[keybinding]
C = T +next<Enter>
```

But that doesn't toggle, it's just one-way.

**Comment by thehunmonkgroup** [comment]
You can add another keybinding to remove `next`, or most likely write a script that detects the absence/presence of the tag and toggles is appropriately.

**Comment by ssnailed** [comment]
For anyone trying to implement this, here's a keybind that will toggle the "next" tag:

```ini
[keybinding]
<Ctrl> n = :!r sh -c 'if task id:{TASK_ID} tags -next; then task id:{TASK_ID} modify +next; else task id:{TASK_ID} modify -next; fi'<Enter>
```
