### ISSUE TITLE
[question] getting rid of "TASKRC override" message

### ISSUE THREAD

**Issue by fenugrec** [vit-project/vit#359]
Hi,
just setting up vit + taskwarrior thus :

$HOME/.config/task/taskrc
$HOME/.config/vit/config.ini

i.e. those are the standard $XDG_CONFIG_HOME locations. Both files are freshly auto-generated.

$TASKRC env is not set. If I read `CUSTOMIZE.md` correctly, vit should search in the XDG base dirs (and indeed it does seem to find those files just fine).

I wonder now, why do I keep getting a "TASKRC override: /home/p/.config/task/taskrc" message everytime I query or edit tasks ? It doesn't seem like I am overriding anything, nor should I need to ?

Thanks!

**Comment by thehunmonkgroup** [comment]
VIT performs some overrides as part of its work, which I'm guessing is the reason for the message. I get it too in my setup:

![2024-09-14_19-30](https://github.com/user-attachments/assets/4ac27082-0b8e-4d07-8094-148a8f35552e)

There may be a TaskWarrior config option to disable this warning, you'd have to check the documentation. I don't think there's anything for VIT to do differently here.

**Comment by fenugrec** [comment]
Thanks for the reply. I wasn't sure if it was coming from vit, as running `task` directly doesn't seem to produce that message

**Comment by thehunmonkgroup** [comment]
I think you get that warning any time you do an override using the `task` command, which VIT does from time to time.

**Comment by fenugrec** [comment]
> There may be a TaskWarrior config option to disable this warning

For others wondering about this, indeed taskwarrior can filter this as part of the 'verbose' settings . see `man taskrc` :

```
verbose=1|0|nothing|list...
   [...]
   you can specify a comma-separated list of verbosity tokens that control specific occasions when output is generated. This list may contain:
   [...]
            override   Notification when configuration options are overridden
```
