### ISSUE TITLE
[VT-17] vit; % should act on uuids not ids

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#39]
_David Patrick on 2013-09-08T17:23:44Z says:_ 

 Keybindings and commands can acts on the selected task, as represented in the .rc by "%=ids", but this is sub-optimal for 3 reasons;

* all tasks have uuids, but only pending tasks have ids
* ids can be changed externally (cronjob, cli, sync) without vit knowing about it.
* the % keybind token (and :! command) only works for reports that display ID

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-09-08T17:23:44Z
Modified: 2014-02-09T01:16:50Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-12-12T23:43:10Z says:_ 

 I agree this should be implemented, but unless I receive a patch this will have to wait.

**Comment by thehunmonkgroup** [comment]
VIT 2.x alpha 1 has been released, and uses uuids for all task interactions

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1
