### ISSUE TITLE
[VT-47] vit; reread command and reread.freq=60 .vitrc setting

### ISSUE THREAD

**Issue by taskwarrior** [vit-project/vit#69]
_David Patrick on 2013-09-08T01:05:26Z says:_ 

 Vit has now idea if something else changes the task data. It's even possible for vit to make a change it doesn't know about 
(for this reason, some keybinds should use the --reread option) 
and I think some reread/refresh/reload command would be a good idea.

A better idea is a .vitrc auto-reread setting as number of seconds between auto-reread.

   auto-reread=60

might be a good default.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-09-08T01:05:26Z
Modified: 2017-02-01T19:08:19Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-02-28T23:20:55Z says:_ 

 There is a way (inotify) for VIT to know whenever one of the .data files changes. If that is implemented, would you still want to implement reread.freq ?

You also bring up another question. If VIT uses inotify as described above, should --reread be deprecated?

**Comment by taskwarrior** [comment]
_Jochen Sprickerhof on 2015-12-01T09:34:33Z says:_ 

 I've written a simple patch to update every 30min. Having an option to configure the timeout would be great, but would need some more coding.
I'm not sure about using inotify, as it would not work if you use taskd to sync.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-12-02T03:11:35Z says:_ 

 Why wouldn't the inotify implementation work if taskd is used to sync? Wouldn't a taskd sync change the .data file and thus inotify would be triggered?

**Comment by pbeckingham** [comment]
[VT-47_0001-Refresh-and-sync-every-30-minutes.patch.txt](https://github.com/scottkosty/vit/files/1755286/VT-47_0001-Refresh-and-sync-every-30-minutes.patch.txt)

**Comment by thehunmonkgroup** [comment]
Can be accomplished with the auto-refresh tools: https://github.com/vit-project/vit/blob/2.x/CUSTOMIZE.md#auto-refreshing-vits-interface
